### PR TITLE
Security Controls AU-02

### PR DESCRIPTION
**Pull request by rnafarrete**
### This pull request changes...

Documented implementation statement for AU-2.  May need to include whether the audit logs contain all the event items that are required by the security control.

### This pull request is ready to merge when...

- [ ] Meets acceptance criteria for the issue 
- [ ] Code is reviewed by someone other than the original author
- [ ] Code is tested 
- [ ] Experience is approved by UX  
- [ ] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [ ] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [ ] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

### CODE REVIEW

**Review by carltonsmith — APPROVED** [review]
LGTM

**Comment by carltonsmith** [comment]
@lfrohlich @hursey013 Waiting to put this PR into QASP until the other security control PRs in QASP have been accepted and merged

**Review by ADPennington — COMMENTED** [review]
@tdrammeh1 and  @PenyinAsare, it would great to have your input here. OFA is reviewing this now, and we were not sure if more details re: which controls are inherited from cloud.gov, login.gov, and which would need to be implemented? cc: @carltonsmith @kniz-raft

**Comment by tdrammeh1** [comment]
System events are captured by cloud.gov and some of the user (developer, tdp account etc.) login events are captured by login.gov. However the Django Admin and system admin are captured in the application. And as correctly pointed out in the notes, the Django Admin provides logs of user actions that can be monitored and reviewed by the application team.

**Comment by ADPennington** [comment]
I think it would be helpful here to provide a bit more specificity on which of the audit logs from cloud.gov, login.gov, or django admin are capturing each of the events included under Part a (i., ii., and iii.). @kniz-raft @carltonsmith cc: @lfrohlich

**Comment by carltonsmith** [comment]
Unblocking this as we can just add screenshots when they are available

**Comment by alexsoble** [comment]
Noting that a couple of logging-related tickets came out of this control: 

+ https://github.com/raft-tech/TANF-app/issues/767
+ https://github.com/raft-tech/TANF-app/issues/762

@carltonsmith, if you notice any more logging features referenced in this security control that will need to be tracked as tickets, please go for it!

**Review by alexsoble — APPROVED** [review]
@tdrammeh1 and @PenyinAsare, this is ready for your review.

**Comment by PenyinAsare** [comment]
This will be a hybrid control. Implementation statement approved

**Comment by carltonsmith** [comment]
> This will be a hybrid control. Implementation statement approved

Thanks @PenyinAsare !

**Pull request merged**
