### PR TITLE
pipenv lock --keep-outdated

### PR DESCRIPTION
**Pull request by andrew-jameson**
## Summary of Changes
same as other ticket, this fails to build though

### CODE REVIEW

**Comment by andrew-jameson** [comment]
@n0remac So here's a minimal update of just the hash and basically nothing else. Not to say this won't just break tomorrow and also the security of an unexpected signature change.

**Comment by andrew-jameson** [comment]
Fwiw, we have a stackoverflow on *why* this happened [here](https://stackoverflow.com/questions/74868303/why-did-my-pypi-choose-a-tarball-hash-yesterday-vs-now-its-using-a-wheel-hash)

The both old and new hashes are available via the official pypi website [here](https://pypi.org/project/python-crontab/2.6.0/#copy-hash-modal-556e5941-9a7b-49bb-8d72-bd7d824f8614)

**Review by ADPennington — APPROVED** [review]
thanks for this @andrew-jameson. glad we've started a discussion on SO 👍🏾

**Review by raftmsohani — APPROVED** [review]
LGTM!

**Comment by raftmsohani** [comment]
My suggestion is: unless it is absolutely necessary we should keep packages at least two versions below the current

**Pull request merged**
