### PR TITLE
2598-staging-deployment-failure-issue

### LINKED ISSUE #2598: [SPIKE] Investigate the failed `staging-deployment` workflow in HHS/TANF-app:main for sprint 75
**Description:**
when attempting to push release `v3.1.2 (sprint 75)` to the staging env, the `staging-deployment` workflow is failing in the HHS repo at the deploy backend step

sprint75_fail

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] STRETCH: #2435 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

### PR DESCRIPTION
**Pull request by raftmsohani**
## Summary of Changes
Pull request closes #2598 _

Removed the migrate and makemigration from gunicorn_start.sh to stop the time consuming migrations which are still due in deployed DBs (specifically prod) from running. Running these migrations during deployment causes timeout for the backend instance and consequently not allowing the deployment job to finish successfully.

## Deployment steps

The new migrations are disabled (in ```gunicorn_start.sh```), as such deployment will be done without new migrations

1. Create a backup from DB. For instructions, see: https://github.com/raft-tech/TANF-app/blob/e4bf0f4feb4918c220265187ab8630696a2aa83a/tdrs-backend/tdpservice/scheduling/BACKUP_README.md
2. Try to restore the backup db into an empty db to ensure backup file is not corrupted.
3. merge this PR into develop
4. Email users and let them know the prod will be down for one hour during working hour. The changes should not take that long, but we will need to have enough time to investigate issues, revert the changes, etc
5. Stop the frontend prod instance to disable users
6. merge the changes into HHS and deploy into prod
7. SSH into backend prod instance
8. perform the following steps:
```
export LD_LIBRARY_PATH=/home/vcap/deps/0/lib/:/home/vcap/deps/1/lib:$LD_LIBRARY_PATH
cd ~/deps/1/bin
./python3 ~/app/manage.py makemigrations 
./python3 ~/app/manage.py migrate
```

### Note: Need to have a contingency plan for reverting the changes 

We are taking a backup from database in step 1 above.

In case of failure and if we decide to revert the changes back to previous commit, we first ssh into the instance:

``` cf ssh tdp-backend-prod```,

and then can try to revert the migration changes to previous migrations.

```
export LD_LIBRARY_PATH=/home/vcap/deps/0/lib/:/home/vcap/deps/1/lib:$LD_LIBRARY_PATH
cd ~/deps/1/bin
./python3 ~/app/manage.py migrate users 0038_user_access_requested_date

```

If for any reason, the migration did not work, we can always restore the database backup, however we should first delete the DB and then restore the DB.
 
## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by George-Hudson — APPROVED** [review]
LGTM

Do we intend this to be a long term solution, or just a one off, and uncomment the `python manage.py migrate` and `python manage.py populate_stts` later?

**Comment by raftmsohani** [comment]
> LGTM
> 
> Do we intend this to be a long term solution, or just a one off, and uncomment the `python manage.py migrate` and `python manage.py populate_stts` later?

The two above changes are temporary only to get the migrations to pass.

**Comment by raftmsohani** [comment]
There was a problem with populating STTs which were causing the e2e test to fail. Added populate_stt to docker-compose and resolved the issue

**Review by jtimpe — APPROVED** [review]

**Review by elipe17 — APPROVED** [review]

**Comment by andrew-jameson** [comment]
@raftmsohani Seeing this on sandbox after manually migrating:

```
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT LocalTime -> 2023-07-25 15:01:07
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT Configuration ->
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . broker -> redis://localhost:6379//
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . loader -> celery.loaders.app.AppLoader
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . logfile -> [stderr]@%INFO
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . maxinterval -> 5.00 seconds (5s)
   2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] ERR [2023-07-25 15:01:07,088: INFO/MainProcess] beat: Starting...
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR [2023-07-25 15:01:07,179: ERROR/MainProcess] Cannot add entry 'name' to database schedule: ValidationError({'interval': ['Only one of clocked, interval, crontab, or solar must be set'], 'crontab': ['Only one of clocked, interval, crontab, or solar must be set']}). Contents: {'task': 'tdpservice.scheduling.tasks.check_for_accounts_needing_deactivation_warning', 'schedule': <crontab: 0 13 * * * (m/h/d/dM/MY)>, 'options': {'expires': 15.0}}
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 320, in update_from_dict
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR entry = self.Entry.from_entry(name,
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 179, in from_entry
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR return cls(PeriodicTask._default_manager.update_or_create(
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR return getattr(self.get_queryset(), name)(*args, **kwargs)
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/managers.py", line 12, in update_or_create
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR self._update_model_with_dict(obj, dict(defaults or {}, **kwargs))
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/managers.py", line 18, in _update_model_with_dict
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR obj.save()
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/models.py", line 580, in save
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR self.validate_unique()
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/models.py", line 565, in validate_unique
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR raise ValidationError(error_info)
   2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR django.core.exceptions.ValidationError: {'interval': ['Only one of clocked, interval, crontab, or solar must be set'], 'crontab': ['Only one of clocked, interval, crontab, or solar must be set']}
   2023-07-25T11:01:07.20-0400 [APP/PROC/WEB/0] ERR [2023-07-25 15:01:07,209: INFO/MainProcess] DatabaseScheduler: Schedule changed.
   2023-07-25T11:01:07.35-0400 [APP/PROC/WEB/0] ERR Visit me at http://localhost:5555
```

I can also deploy to a11y since it is typically behind on migrations. How would you like to approach troubleshooting this?

**Comment by raftmsohani** [comment]
> 

This looks like a different error, I think it is because we try to set "schedule", "crontab" and "interval" at the same time. I will take a look, but this doesn't seems to be relevant to the migrations in question

**Comment by raftmsohani** [comment]
> This looks like a different error, I think it is because we try to set "schedule", "crontab" and "interval" at the same time. I will take a look, but this doesn't seems to be relevant to the migrations in question

UPDATE July 25th: I am still looking into this problem. Trying to find solution to this

**Comment by raftmsohani** [comment]
> @raftmsohani Seeing this on sandbox after manually migrating:
> 
> ```
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT LocalTime -> 2023-07-25 15:01:07
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT Configuration ->
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . broker -> redis://localhost:6379//
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . loader -> celery.loaders.app.AppLoader
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . logfile -> [stderr]@%INFO
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] OUT . maxinterval -> 5.00 seconds (5s)
>    2023-07-25T11:01:07.08-0400 [APP/PROC/WEB/0] ERR [2023-07-25 15:01:07,088: INFO/MainProcess] beat: Starting...
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR [2023-07-25 15:01:07,179: ERROR/MainProcess] Cannot add entry 'name' to database schedule: ValidationError({'interval': ['Only one of clocked, interval, crontab, or solar must be set'], 'crontab': ['Only one of clocked, interval, crontab, or solar must be set']}). Contents: {'task': 'tdpservice.scheduling.tasks.check_for_accounts_needing_deactivation_warning', 'schedule': <crontab: 0 13 * * * (m/h/d/dM/MY)>, 'options': {'expires': 15.0}}
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR Traceback (most recent call last):
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 320, in update_from_dict
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR entry = self.Entry.from_entry(name,
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/schedulers.py", line 179, in from_entry
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR return cls(PeriodicTask._default_manager.update_or_create(
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR return getattr(self.get_queryset(), name)(*args, **kwargs)
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/managers.py", line 12, in update_or_create
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR self._update_model_with_dict(obj, dict(defaults or {}, **kwargs))
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/managers.py", line 18, in _update_model_with_dict
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR obj.save()
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/models.py", line 580, in save
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR self.validate_unique()
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR File "/home/vcap/deps/1/python/lib/python3.10/site-packages/django_celery_beat/models.py", line 565, in validate_unique
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR raise ValidationError(error_info)
>    2023-07-25T11:01:07.18-0400 [APP/PROC/WEB/0] ERR django.core.exceptions.ValidationError: {'interval': ['Only one of clocked, interval, crontab, or solar must be set'], 'crontab': ['Only one of clocked, interval, crontab, or solar must be set']}
>    2023-07-25T11:01:07.20-0400 [APP/PROC/WEB/0] ERR [2023-07-25 15:01:07,209: INFO/MainProcess] DatabaseScheduler: Schedule changed.
>    2023-07-25T11:01:07.35-0400 [APP/PROC/WEB/0] ERR Visit me at http://localhost:5555
> ```
> 
> I can also deploy to a11y since it is typically behind on migrations. How would you like to approach troubleshooting this?

Looking deeper into this, the error looks like a false error, the periodic task already exist in the db and looks like the app tries to add the same schedule and fails. But it is safe failure

**Review by andrew-jameson — APPROVED** [review]

**Comment by ADPennington** [comment]
@raftmsohani below are the results for step 1. I wasnt sure if i was supposed to do the backup for the `aws-rds` service or the `aws-elasticsearch` service so i tried both. It appears the former worked fine. Also, im not quite sure how to do step 2, specifically what should the name of the empty db be? 

---

<redacted>  contact me for the commands

**Review by ADPennington — APPROVED** [review]
@raftmsohani @andrew-jameson i ran the db backup and restore commands and saved them [here](https://gorafttech.sharepoint.com/:u:/r/sites/TDRSResearchDesign/Shared%20Documents/Dev/dev/qasp-2598.sh?csf=1&web=1&e=NxYowL). 

I can go thru the other manual steps once this merges to `develop` or `hhs:main`

**Comment by raftmsohani** [comment]
> @raftmsohani below are the results for step 1. I wasnt sure if i was supposed to do the backup for the `aws-rds` service or the `aws-elasticsearch` service so i tried both. It appears the former worked fine. Also, im not quite sure how to do step 2, specifically what should the name of the empty db be?
> 
> contact me for the commands

We discussed this over the chat. The Backup will be for the RDS, ES will be synced after restore.

**Pull request merged**
