### PR TITLE
chore(1415): bump django-admin-508 to 0.2.0

### LINKED ISSUE #1415: Django Admin - Visual consistency fixes
**Description:**
**As a django admin user, I want elements to appear consistently cross-device and cross-browser**

On Chrome, there is no visible border for the search box or the action drop-down (see screenshot) which may make it difficult for users to perceive that these controls are actionable (or that they even exist). Suggest using the standard border design similar to what is in place in the filter dropdowns in right column of the page.

e.g. Search input field appears without its border on some devices (see screen capture below--Note lack of a border around search field):
image 

image

**Acceptance Criteria:** 
- [ ] All instances of visual differences across devices due to specific style values not being rendered are corrected
- [ ] Testing Checklist has been run and all tests pass
- [ ] Padding is fixed across the app to the pre-sidebar style
- [ ] Fix styles of `Add` buttons on list views
- [ ] Address warnings in console
- [ ] Fix size of filter dropdowns
- [ ] README is updated, if necessary

**Stretch Goal**
- [x] Hide the Add User button in Django Admin for TDRS

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Force styles of input elements using css
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
[HackMD notes](https://hackmd.io/3zR7vj7GQ7uidJmLR-eCYw?view#Follow-On-Stuff)

### PR DESCRIPTION
**Pull request by jorgegonzalez**
## Summary of Changes

This PR updates django-admin-508 to the latest version to address various fixes for visual inconsistencies in several Django Admin pages. This PR also disables the ability to add users via Django Admin, per @ADPennington's request in #1664.

Pull request closes #1415

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Navigate to the Django Admin page and login.
1. If possible, compare the Django Admin page of this branch with the one deployed on staging
1. Ensure the changes visible in the screenshots below are present
> *Demo GIF(s) and screenshots for testing procedure*

Screen Shot 2022-04-15 at 9 07 47 AM
Screen Shot 2022-04-14 at 1 33 54 PM
Screen Shot 2022-04-14 at 1 33 36 PM

## Tabletop

- [ ] Ready for Tabletop (Reviewer check this)
- [ ] Tabletop scheduled (Assignee check this)
- [ ] Tabletop approval 

## Deliverables
_More details on how deliverables herein are assessed included [here](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by reitermb — APPROVED** [review]
All looks good to me! Previous a11y fixes not impacted negatively & it's definitely looking cleaner now. 🚀

**Comment by ADPennington** [comment]
@jorgegonzalez noticed that the close menu is still right aligned in a11y env. cc: @ttran-hub

**Comment by jorgegonzalez** [comment]
I feel like that is caused by a deployment issue @ADPennington

**Comment by ADPennington** [comment]
> I feel like that is caused by a deployment issue @ADPennington

re-deploy via label appears to have worked @jorgegonzalez @ttran-hub 
1415p2

**Comment by ttran-hub** [comment]
image
@ADPennington @jorgegonzalez Can you check or re-deploy the latest, the current environment does not match latest.  The Close menu is right align and add user selection still presents.

**Comment by ADPennington** [comment]
@ttran-hub should be re-deployed with latest changes now. https://tdp-backend-a11y.app.cloud.gov/admin/users/user/

cc: @jorgegonzalez

**Comment by ttran-hub** [comment]
image
The Close Menu was left aligned after re-deployed this morning, but for some reason it's back to the right alignment. 
@jorgegonzalez @reitermb Can you double check the highlighted checkbox, there is an empty table header error flag.  The first tab stop at the checkbox is good but there seemed to be a second tab stop at the same check box that flagged with the empty table header.  Thanks! cc @ADPennington

**Comment by reitermb** [comment]
> image The Close Menu was left aligned after re-deployed this morning, but for some reason it's back to the right alignment. @jorgegonzalez @reitermb Can you double check the highlighted checkbox, there is an empty table header error flag. The first tab stop at the checkbox is good but there seemed to be a second tab stop at the same check box that flagged with the empty table header. Thanks! cc @ADPennington

I'm actually having some trouble getting the checkbox column to show up at all now—not sure if there was a new code change? @jorgegonzalez 

I know that last time we changed the checkboxes they were functional—in the django PR for fixing the select all, but I'll have to get them back in front of me to know about the error. Thoughts also welcomed Jorge on whether this would be inside the scope of this ticket or if spinning one off would be better.

**Comment by jorgegonzalez** [comment]
> > image The Close Menu was left aligned after re-deployed this morning, but for some reason it's back to the right alignment. @jorgegonzalez @reitermb Can you double check the highlighted checkbox, there is an empty table header error flag. The first tab stop at the checkbox is good but there seemed to be a second tab stop at the same check box that flagged with the empty table header. Thanks! cc @ADPennington
> 
> 
> 
> I'm actually having some trouble getting the checkbox column to show up at all now—not sure if there was a new code change? @jorgegonzalez 
> 
> 
> 
> I know that last time we changed the checkboxes they were functional—in the django PR for fixing the select all, but I'll have to get them back in front of me to know about the error. Thoughts also welcomed Jorge on whether this would be inside the scope of this ticket or if spinning one off would be better. 

This, again, seems to me like the deployment was overwritten. Are you sure the current changes were deployed when this was noticed? That Close Menu button should be left aligned for example.

**Comment by jorgegonzalez** [comment]
I need access to django admin in a11y to test this @ADPennington @andrew-jameson

**Comment by ADPennington** [comment]
> I need access to django admin in a11y to test this @ADPennington @andrew-jameson

access granted. note that your access_request flag is an ❌

**Comment by jorgegonzalez** [comment]
> > I need access to django admin in a11y to test this @ADPennington @andrew-jameson
> 
> access granted. note that your access_request flag is an ❌

That flag is not needed to access django admin

**Comment by reitermb** [comment]
Confirming that there's a tab stop generating that header error @ttran-hub but that it's outside the scope of this particular issue. We should connect re: what the screenreader behavior is on your end / whether it amounts to something we'd need to spin up a separate ticket to tweak. 

cc @ADPennington

**Comment by ttran-hub** [comment]
> Confirming that there's a tab stop generating that header error @ttran-hub but that it's outside the scope of this particular issue. We should connect re: what the screenreader behavior is on your end / whether it amounts to something we'd need to spin up a separate ticket to tweak.
> 
> cc @ADPennington

Let connect re: extra tab stop, otherwise LGTM

**Comment by ADPennington** [comment]
@reitermb we think this is a pretty easy fix, but if it is big enough to warrant a new issue, can you create that issue asap so we can approve this one? it would be added to backlog as low priority. cc: @ttran-hub

**Comment by stevenino** [comment]
> @reitermb we think this is a pretty easy fix, but if it is big enough to warrant a new issue, can you create that issue asap so we can approve this one? it would be added to backlog as low priority. cc: @ttran-hub

Agree this is outside the scope of this ticket. If that is the only issue with this PR, then it should be approved. Seems like there needs to be a separate conversation to see if the stop-gap amounts to a new ticket but regardless it should not block the closure of this ticket. cc: @reitermb @ADPennington

**Comment by reitermb** [comment]
@ttran-hub @ADPennington Spun up #1775 to document the extra tab stop issue

**Comment by stevenino** [comment]
@ADPennington @ttran-hub Can you approve your reviews if the PR looks good to you?

**Review by ADPennington — APPROVED** [review]
@andrew-jameson can you look into this before merge? related to recent pipfile.lock update ?

**Pull request merged**
