### PR TITLE
Security Controls SC-28

### PR DESCRIPTION
**Pull request by carltonsmith**
### Summary of Changes

Security Control documentation for SC-28

### CODE REVIEW

**Review by kniz-raft — APPROVED** [review]
LGTM!

**Comment by alexsoble** [comment]
(Covering for @ADPennington on QASP review for a bit!)

**Review by alexsoble — APPROVED** [review]
@tdrammeh1 and @PenyinAsare, this is ready for your review.

**Comment by PenyinAsare** [comment]
by the use of the word "will" does it indicate that this is a planned control or its currently in place? (same question apply for SC-28(1)

**Comment by carltonsmith** [comment]
> by the use of the word "will" does it indicate that this is a planned control or its currently in place? (same question apply for SC-28(1)

@PenyinAsare No, this has already been implemented. I used "will" because we are not yet in production, but I have updated the verbiage to reflect the state of the implementation. Thanks!

**Comment by PenyinAsare** [comment]
Approved

**Review by lfrohlich — APPROVED** [review]
👍

**Pull request merged**
