### PR TITLE
Security Controls: SC-08

### PR DESCRIPTION
**Pull request by carltonsmith**
### Summary of Changes

Adds documentation for SC-08

### CODE REVIEW

**Review by kniz-raft — APPROVED** [review]

**Review by jtwillis92 — APPROVED** [review]

**Review by tdrammeh1 — COMMENTED** [review]
Please add the version of TLS being used.

**Comment by carltonsmith** [comment]
> Please add the version of TLS being used.

Thanks @tdrammeh1 - I have updated the doc with the information provided in the cloud.gov docs. Please take a look and let me know if this does the trick.

**Review by tdrammeh1 — COMMENTED** [review]
This looks good. Thanks

**Comment by PenyinAsare** [comment]
Hybrid. Approved

**Pull request merged**
