### PR TITLE
Adds finalized Knowledge Center Content

### LINKED ISSUE #1693: As a grantee pilot user I want to be able to access the knowledge center through project updates environment
**Business Value**
As a Grantee Pilot User, 
I want to be able to be able to help myself navigate through TDP
So that I can insure my understanding of the TDP platform and continue to do my job

**Description**
Delivers a design for an in-app knowledge base which aggregates all onboarding/support content. May also contain existing materials like data coding instructions.

4/25
Planning to utilize Project Updates environment & templates to host this in the pilot

**AC:** 
- [ ] The design is consistent with the team’s past decisions, or a change is clearly documented 
- [ ] The design is usable, meaning... 
   - [ ] It uses [USWDS components and follows it’s UX guidance](https://designsystem.digital.gov/components/), or a deviation is clearly documented 
   - [ ] Language is intentional and [plain](https://plainlanguage.gov/guidelines/); placeholders are clearly documented 
   - [ ] It follows [accessibility guidelines](https://accessibility.digital.gov/) (e.g. clear information hierarchy, color is not the only way meaning is communicated, etc.) 
   - [ ] If feedback identifies bigger questions or unknowns, create additional issues to investigate 
- [ ] Relevant user stories are documented.

**Notes**
All other onboarding tickets deliver the actual onboarding content, this just aggregates it. Blocked by other onboarding content tickets as it requires insight into the full set of content. 
Likely knowledge base areas:

- [ ] Creating & managing a login.gov account
- [ ] Logging into TDP, Getting Access
- [ ] Framing TDP functionality (Data Submission/Resubmission, Requirements for Data and How to Submit Complete Resubmissions)
- [ ] TDP Release Notes (Potential way to frame feature overview from homepage & Getting Started email)
- [ ] How To: Ask Questions, Get Support, Give Feedback

May also be a good place to host some content from https://tanfdata.org/

Design will likely be modeled after informational USWDS page templates, e.g. USWDS' own getting started guide https://designsystem.digital.gov/documentation/getting-started/developers/phase-one-install/

**Tasks**
- [ ] Draft information architecture (page hierarchy, order, labeling)
- [ ] Add links to all content to be hosted in knowledge base
- [ ] Share for internal review
- [ ] Revision as needed

**Documentation**
- Draft in hack.md
[existing login.gov ](https://hackmd.io/t1lPMv2vQkCxcDhtPxrbCg)
[new login.gov](https://hackmd.io/I5zu3_jNSZem9Y2cQpb2TA?both) 
**DD**
- [ ] @lfrohlich has reviewed and signed off

### PR DESCRIPTION
**Pull request by reitermb**
This PR closes #1693 

## Summary of Changes
- Adds subdirectory to project updates environment to host Knowledge Center
- Adds Knowledge center content
- Bumps USWDS CSS version to support needed content
- Bumps jquery version
- Adds [Lity](https://sorgalla.com/lity/) to applicable pages to support accessible lightboxes
- Adds MVP version of "Back to top" functionality via anchor tags on applicable (read: long) pages

## How to Test
This PR is identical to what's currently hosted in my Project Updates environment Staging Repo. It can be accessed at: https://reitermb.github.io/Test/knowledge-center/ and browsed as a repo: https://github.com/reitermb/Test

### CODE REVIEW

**Comment by reitermb** [comment]
cc @ttran-hub @ADPennington 
Re: Prior a11y review

- Sidenav List element has direct children that are not allowed inside <li> elements looks like it was a false positive 
- All broken links should be working now
- All headings should be in the correct hierarchical order now
- Lengthy pages have a basic back to top link at the end now (there are ways to make it fancier, e.g. smooth scrolling and/or floating buttons in the future, but both would have added quite a bit of scope to do accessibly right now)
- Page titles should now be descriptive and unique
- Added what should be a fully accessible lightbox to all images (focus should be correctly trapped when the lightbox is open, alt text should be accessible by screenreaders in lightbox mode, keyboard nav should be supported for entering and exiting lightbox)

**Comment by ADPennington** [comment]
@ttran-hub this is ready for `gov a11y review`. @reitermb please connect with Thomas for a walk-through of the changes you mentioned 🆙

**Comment by ttran-hub** [comment]
Thanks @reitermb, the nav nesting fixes the list element under the above bullet one. a11y LGTM!  🚀

**Review by ADPennington — APPROVED** [review]
👍🏾 thanks @reitermb @lilybl1. cc: @ttran-hub @lfrohlich

**Pull request merged**
