### PR TITLE
Security controls: AC-07

### PR DESCRIPTION
**Pull request by kniz-raft**
### Summary of Changes
_Adds security control implementation statement_
_Addresses issue #656_

### CODE REVIEW

**Review by carltonsmith — APPROVED** [review]
LGTM

**Review by alexsoble — APPROVED** [review]
@tdrammeh1 and @PenyinAsare, this is ready for your review.

**Comment by PenyinAsare** [comment]
@carltonsmith How do is there a direct link to the screenshots??

**Comment by carltonsmith** [comment]
> @carltonsmith How do is there a direct link to the screenshots??

Hi @PenyinAsare - if you follow [this link](https://github.com/raft-tech/TANF-app/pull/801/files?short_path=53886f7#diff-53886f7c2b0aed9a032eec0a6bb3b2c9682dda0146009b65d7410d6b6148740f) you'll be able to view them and click on them if you want to see them individually

**Comment by PenyinAsare** [comment]
Approved

**Pull request merged**
