### PR TITLE
jquery bump & shutdown placeholder

### PR DESCRIPTION
**Pull request by reitermb**
## Summary of Changes
Placeholder PR to support fast-tracked deployment of shutdown info notice on the knowledge center. Currently:
- Adds info banner with shutdown placeholder language
- Takes the opportunity to bump knowledge center jquery version (we can re-purpose this PR for standard knowledge center updates in the case of no shutdown)

Neither change should have any impact on a11y but it's live and reviewable here if @ttran-hub wants to take a look https://reitermb.github.io/Test/knowledge-center/

### CODE REVIEW

**Comment by reitermb** [comment]
cc @lfrohlich @ADPennington @Smithh-Co @ttran-hub

**Comment by ADPennington** [comment]
@reitermb Is it possible to get the banner to be a different color? to distinguish between standard info in KC? 

mostly just curious. looks fine to me.

**Comment by reitermb** [comment]
> @reitermb Is it possible to get the banner to be a different color? to distinguish between standard info in KC?
> 
> mostly just curious. looks fine to me.

It's easiest if we stick to the "stock" colors of the [alert component](https://designsystem.digital.gov/components/alert/) but it's a light lift to override it to something custom as well if we want to. 

Any thoughts on the yellow flavor? 

image

**Comment by ADPennington** [comment]
This looks good to me. if this is stock I'd vote for this. but generally, I'm in favor of keeping stock, as you suggest. 🙂

**Comment by reitermb** [comment]
> This looks good to me. if this is stock I'd vote for this. but generally, I'm in favor of keeping stock, as you suggest. 🙂

Great, it is indeed. Swapped out and should be deploying shortly!

**Comment by ttran-hub** [comment]
> > This looks good to me. if this is stock I'd vote for this. but generally, I'm in favor of keeping stock, as you suggest. 🙂
> 
> Great, it is indeed. Swapped out and should be deploying shortly!

Thanks @reitermb, It looks good to me. Merge material only if a government shutdown occurs after October 1.  cc @ADPennington

**Comment by ADPennington** [comment]
> > > This looks good to me. if this is stock I'd vote for this. but generally, I'm in favor of keeping stock, as you suggest. 🙂
> > 
> > 
> > Great, it is indeed. Swapped out and should be deploying shortly!
> 
> Thanks @reitermb, It looks good to me. Merge material only if a government shutdown occurs after October 1. cc @ADPennington

yep! we'll approve this on 10/2 if we need it @ttran-hub @reitermb @lfrohlich @Smithh-Co.

**Comment by jtimpe** [comment]
@reitermb @ADPennington is this pr still relevant and, if so, is any action needed from dev?

**Pull request closed without merging**
