### PR TITLE
Updates & Enhancements to Project Updates / Knowledge Center

### PR DESCRIPTION
**Pull request by reitermb**
## Summary of Changes
Adds most recent project update to project updates site
Adds knowledge center enhancements:
- Resource cards for existing/new login.gov getting started flow
- Go to TDP button in the nav
- Bumps query to 3.6.1

## How to Test
Knowledge center in test environment: https://reitermb.github.io/Test/knowledge-center/index.html
Project updates in test environment: https://reitermb.github.io/Test/

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### CODE REVIEW

**Comment by reitermb** [comment]
Can't seem to tag as a reviewer, but noting for @ttran-hub that the knowledge center changes should get government a11y review.

**Comment by reitermb** [comment]
Also noting that the link in the project update to the full research synthesis will be broken until the synthesis PR is merged

**Comment by ADPennington** [comment]
@ttran-hub this is ready for gov a11y review. Please note:

- we need review on:
  -  the `getting started` page [here](https://reitermb.github.io/Test/knowledge-center/index.html), which now includes a link to the TDP frontend and resource cards for signing into TDP (see below)

2157p1

  - the ` August 2022 project updates` page [here](https://reitermb.github.io/Test/) which now includes lessons learned from v2.0.

**Comment by ttran-hub** [comment]
> @ttran-hub this is ready for gov a11y review. Please note:
> 
> * we need review on:
>   
>   * the `getting started` page [here](https://reitermb.github.io/Test/knowledge-center/index.html), which now includes a link to the TDP frontend and resource cards for signing into TDP (see below)
> 

@reitermb @ADPennington The addition of the Resource cards for existing/new login.gov getting started flow and Go to TDP button looks good for A11y review.  🚀

> * the ` August 2022 project updates` page [here](https://reitermb.github.io/Test/) which now includes lessons learned from v2.0.

@reitermb @ADPennington One minor quick fix request is updating the title to **August 2022**. The title is currently read as April 2022 ( <title>TANF Data Portal Project Updates - **April 2022**</title>\n ).  Other than that, the `August 2022 project updates` page looks good for the A11y review.

**Comment by reitermb** [comment]
> > @ttran-hub this is ready for gov a11y review. Please note:
> > 
> > * we need review on:
> >   
> >   * the `getting started` page [here](https://reitermb.github.io/Test/knowledge-center/index.html), which now includes a link to the TDP frontend and resource cards for signing into TDP (see below)
> 
> @reitermb @ADPennington The addition of the Resource cards for existing/new login.gov getting started flow and Go to TDP button looks good for A11y review. 🚀
> 
> > * the ` August 2022 project updates` page [here](https://reitermb.github.io/Test/) which now includes lessons learned from v2.0.
> 
> @reitermb @ADPennington One minor quick fix request is updating the title to **August 2022**. The title is currently read as April 2022 ( <title>TANF Data Portal Project Updates - **April 2022**</title>\n ). Other than that, the `August 2022 project updates` page looks good for the A11y review.

Nice catch! Went ahead and committed a fix for that.

**Review by ADPennington — APPROVED** [review]
👍🏾

**Pull request merged**
