### PR TITLE
Release notes 3.7.0

### LINKED ISSUE #3149: Sprint 110 Release Notes/Knowledge Center
**Description:**
We've received feedback about the ftanf page. its outdated and suggests the transition from tdrs to tdp is still in progress. just a heads up that we need a ticket to track an update to this page. 

**AC:**
- [x] Content drafted in Gitbook
- [ ] Changes staged in Knowledge Center Test environment
- [ ] A11y tested

**Tasks:**
- [x] Draft content for: 
   - [x] ftanf page to reflect the legacy system having been decommissioned
   - [x] Fiscal vs Calendar table release notes 

**Notes:**
From August 15 Release Notes:
We have relaxed TDP's data processing requirements to help ensure that the data in your files can still be processed even if these files have an invalid value for the [update indicator](https://www.acf.hhs.gov/sites/default/files/documents/ofa/transmission_file_header_trailer_record.pdf). However, the TDP system expects the header update indicator to be set to "D" and if not, your error report will still include an error asking you to correct it. [Read more about the header record](https://tdp-project-updates.app.cloud.gov/knowledge-center/viewing-error-reports.html) and [how to export complete data using fTANF.](https://reitermb.github.io/Test/knowledge-center/exporting-complete-data-using-ftanf.html)

### PR DESCRIPTION
**Pull request by reitermb**
## Summary of Changes
Closes #3149 
Adds release notes for 3.7.0 on October 24th
Updated pages:
- [Index (release notes)](https://reitermb.github.io/Test/knowledge-center/index.html)
- [Submitting data (new fiscal/calendar guidance)](https://reitermb.github.io/Test/knowledge-center/uploading-data.html)
- [Complete data w/ FTANF (legacy system mentions)
](https://reitermb.github.io/Test/knowledge-center/exporting-complete-data-using-ftanf.html)

## Accessibility
All changes returning clean scans
Index
image

Submitting Data
image

Complete data w/ FTANF
image

### CODE REVIEW

**Review by ADPennington — APPROVED** [review]
LGTM👍🏾

**Review by klinkoberstar — APPROVED** [review]

**Comment by andrew-jameson** [comment]
@victoriaatraft Given the significant changes wrt to Reparsing, I have updated version to be 3.7.0 -- let me know if this is problematic. 

[Release PR link](https://github.com/HHS/TANF-app/pull/549)

**Comment by reitermb** [comment]
> @victoriaatraft Given the significant changes wrt to Reparsing, I have updated version to be 3.7.0 -- let me know if this is problematic.
> 
> [Release PR link](https://github.com/HHS/TANF-app/pull/549)

Thanks for the note @andrew-jameson ! I've adjusted the email and the PR accordingly.

**Comment by lfrohlich** [comment]
> @victoriaatraft Given the significant changes wrt to Reparsing, I have updated version to be 3.7.0 -- let me know if this is problematic.
> 
> [Release PR link](https://github.com/HHS/TANF-app/pull/549)

@ADPennington want to make sure you saw this

**Review by lfrohlich — APPROVED** [review]
LGTM

**Pull request merged**
