### PR TITLE
229: As a new user, I can select an applicable STT or OFA category from the combo box

### PR DESCRIPTION
**Pull request by hilvitzs**
### This pull request changes...

- Adds `Associated State, Tribe, or Territory` dropdown to `Request Access` page

**CONTEXT**
This PR adds the Combo Box to the EditProfile form. In order to get the STT's for the Combo Box options I created an action called fetchStts that will grab the alphabetical list of STT's: [fetchStts](https://github.com/raft-tech/TANF-app/pull/311/files#diff-2c5d77e0ddb9357aacc9a1180c367f51628d7b068f3bb846c164345ef0994858R8). 
There are also corresponding tests [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-df6455798c22bd2bf8fd7a7d9901c6921db754c93e249895b23386c2ef529745R1).

Next, I created a ComboBox [component](https://github.com/raft-tech/TANF-app/pull/311/files#diff-14ebc5c57209f87290a40843d6b7a11acee372e096aeb14c7e5e23173165fb5eR1-R43) to be imported by EditProfile and rendered inside the form [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-f5e3a7ebf1f48aa3b8ccbceaae0ffdd8b97d4d3278f4d23f6bca0d49d15b6201R47).
There are also corresponding tests [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-0a582016400dfdab52beb06254773286d39728004e38c548bf3592c7843ed3f0R1-R101).

In `tdrs-frontend/src/components/Routes/Routes.test.js`, I had to mock the stts that were in the store in order for the tests to pass.

In `tdrs-frontend/src/reducers/index.js`, I imported the stt reducer created [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-62b3c1f2157df186b14993a786b592d82ad40859a45c3ce7731d46e0aa44ad9aR1-R40).
These are the tests [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-2e8213cc684440c812cc77af419dc3a8c137f824808353a143ec05f0ebb33c46R1-R77).

There are also a few other small cleanup changes: 
- Remove linter rule that I had to make in order to try `react-select` [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-15bb2b60ccc05f72372c139edf4d47d05484ba9143c941fc112560721ae5e9beL27).

- Snyk found a vulnerability in `open-sass` version 0.11.4 so I added a resolution for 0.11.5 on Snyk's suggestions [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-590346b8b3c98788304d0e95c0585544e2d2b9f3c9f6c8b57d46bec7c7606b14R38).

- Created an index.js file for the `ComboBox` component so that it can be imported as default [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-f9f06e6cb4f385fc2f5ddd021ed976ccbd7a5bde5f33ad70788e5287838274d0R1-R3).

- Removed tsconfig.json which was automatically created experimenting with a typescript file earlier in the project.

All of the rest of the changes on this PR are coming from the `backend/229/stts-endpoint` branch.

**NEEDS FEEDBACK**
I think I finally got the USWDS component working. Here were the outstanding issues that SHOULD now be fixed:

- When a selection is made the dropdown remains open and does not close until you click somewhere outside of the dropdown. (This is fixed when the id attribute on the select element does NOT match the htmlFor attribute on the label element.)  
*I am going to look at opening an issue on USWDS repo to fix this. The select's id is not coming through even in the docs example. For now, this is probably an accessibility concern because the id from the `select` is different than the `for` attribute on the `combo-box` div. It gets a little bit complicated by the fact that the actual selection is done based on a `ul` element that is added by the `combo-box` javascript. The elements I'm referring to are [here](https://github.com/raft-tech/TANF-app/pull/311/files#diff-14ebc5c57209f87290a40843d6b7a11acee372e096aeb14c7e5e23173165fb5eR15-R18)
- On mobile, voiceover has a hard time deciding on the focus between the options and the input and kind of jumps back and forth. *FIXED - not sure why this was happening but seems to be fixed with the same line of code as the next issue*
- When tabbing through the elements, if you tab into and then out of the combo box then it selects the first option automatically. (I think this is caused by the async fetching of the stt data - it is fixed when using an actual list of options, from the docs for example.) 
*FIXED with [this line](https://github.com/raft-tech/TANF-app/pull/311/files#diff-14ebc5c57209f87290a40843d6b7a11acee372e096aeb14c7e5e23173165fb5eR12). Somehow the select element was getting a value even without a selection being made. This sets it back to blank which fixes the issue.*

### [AC] This pull request is ready to merge when...

- [ ] Tests have been updated (and all tests are passing)
- [ ] Vulnerability Scan Test (Zap) has no high/critical CVEs
- [ ] Linting Tests (ESLint for UI and Flake8 for Python)
- [ ] Unit Tests ( including a code coverage test report)
- [ ] Accessibility Tests (Pa11y UI Only)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The experience passes a basic manual accessibility audit (keyboard nav, screen reader, text scaling) OR an exemption is documented
- [ ] The change has been documented
- [ ] Associated OpenAPI documentation has been updated
- [ ] Changelog is updated as appropriate

### [DoD] This feature is done when...

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Comment by alexsoble** [comment]
👋 Hi @carltonsmith and @hilvitzs! Thanks for tagging me in on my first PR review!

@hilvitzs Thank you for raising the a11y question, it's a great one! I think it would be great to pull in Robert Jolly for a quick a11y standards consultation. I'll ping him and see if we can gather up for a ~30 minute a11y standards consultation early next week, does that sound like a good plan?

**Comment by hilvitzs** [comment]
@alexsoble Happy to have you available to look over things! I think that sounds like a great plan although things have changed a little bit today as far as the dropdown. @reitermb was doing a preliminary check and ran into some pretty significant issues with voiceover on mobile devices in the `react-select` package that we were using. He is talking with Shubhi and Christine today about switching over to a new package that we found. I think it would be great if we could set something up with Robert early next week to check over the new package.

**Comment by alexsoble** [comment]
@hilvitzs Sounds like a plan! 👍 😄

**Comment by RafterGit** [comment]
Making a note we held an accessibility pairing session with Robert Jolly. Gained some good insight on his testing practices and we have some action items in flight to consolidate our approaches.

@hilvitzs found a solution to the USWDS combo-box issue and is currently testing with @reitermb  today(10/7/2020)

**Comment by alexsoble** [comment]
@RafterGit Thanks for the update!

**Comment by hilvitzs** [comment]
@alexsoble @RafterGit I wanted to give a more thorough update regarding the accessibility concerns that @reitermb found.

There are three major concerns:

- When a selection is made the dropdown remains open and does not close until you click somewhere outside of the dropdown
- On mobile, voiceover has a hard time deciding on the focus between the options and the input and kind of jumps back and forth. I included a video that @reitermb took of the issue.

The bad news is that I am not doing anything different than the example from USWDS so I have to assume that this is just another example of the combo box from USWDS not being good for use with React. I am looking at trying to solve the issues but these could be equally as hard to fix as the rendering problem was because I'll have to dig into the USWDS component code to figure out why it isn't working the way it should.

**Comment by alexsoble** [comment]
Thanks for the update @hilvitzs. Darn, this sounds frustrating! 

It sounds like the desired combination of USWDS + React + custom theming + high a11y standards is proving tricky to achieve. I see in the PR history that the team tried using the Trussworks library but then removed it.

I know a former 18F dev, current TTS dev (TTS is our parent agency) who did a bunch of work and thinking on USWDS + React. I could see if he's available for a quick consult to coach us on this and potentially suggest solutions.

**Comment by hilvitzs** [comment]
@alexsoble That would be great just to see if they have any insight. Some of these issues are just so bizarre. For example, the issue that I am having where the dropdown doesn't close when a selection is made is fixed only if the `htmlFor` attribute on the label and the `id` and `name` attributes on the `select` element do NOT match. That's going to be an accessibility violation on its own but that's the only way that it will close on a selection.

**Comment by hilvitzs** [comment]
@alexsoble Just leaving this here so I don't forget tomorrow. I looked at the USWDS docs example of the combo box and it looks like they are also not having an ID come through from the HTML even without React.

Screen Shot 2020-10-08 at 3 28 31 PM

**Comment by hilvitzs** [comment]
Hey @alexsoble! This is ready for an informal review when/if you have a moment. I'm happy to answer any questions but it seems to be working from our side.

**Comment by alexsoble** [comment]
@hilvitzs Excellent, and congrats on working your way through challenging combo box issues! I see a lot of grit and determination in your work here!

**Comment by alexsoble** [comment]
I sent some resources on the dev channel in Teams little while back about adding more context to pull requests to help with reviews — I'll tag you on the thread in Teams. 

The PR description just mentions adding the dropdown as the change, but with 55 files changed I'd be curious to know more about all the changes that enable or relate to the dropdown feature. 👀

**Comment by hilvitzs** [comment]
Thanks for the info on context! I added some extra information to the PR description and some links. Hopefully, that helps but I'm happy to provide more or make changes to whatever is most helpful. I know the 55 files are a lot. I think there are only about 15 on the front end, the rest were changes made on the back end that I had to pull in in order to work on the Combo Box.

**Comment by carltonsmith** [comment]
I am closing this PR to issue it against the backend, since that is where it was branched from

**Pull request closed without merging**
