### PR TITLE
fix/2140 scroll upload alert into view

### LINKED ISSUE #2140: As a grantee user submitting data I always want to see the confirmation/error message
**Description:**

Pilot research showed us that most of our participants were using TDP at resolutions that cut off the success/error banner on the Data Files submission page. This ticket should deliver an enhancement that sets focus to said banner when Submit is clicked. 

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Focus shifts to banner when Submit is clicked
- [ ] Banner is not in the normal tab order (i.e. you'll only be able to focus it in screenreader mode or by clicking submit)
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Add function to set focus to error / success banner
- [ ] Check to make sure the banner is not tabbable normally (without using a screen-reader) 
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Page headings are a good example of focused but not in normal tab order behavior. When you land on a page in TDP focus is set to the main heading, but if you start tabbing around you can't land back on the heading. 
Testing multi-file including one fail, test at a high browser zoom to simulate low resolution.

### PR DESCRIPTION
**Pull request by jtimpe**
## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #2140

* When a data file is submitted, scroll the alert banner (success or failure) into view. Particularly useful for people with low-resolution monitors and small screens.

## How to Test
```
cd tdrs-frontend && npm run start
cd tdrs-backend && docker-compose up
```

1. Open http://localhost:3000/ and sign in.
1. Make your browser window pretty small, so that you have to scroll to access different functions of the page.
1. Navigate to the Data Files page, make a search selection, scroll down to a data section, and submit a valid file.
   * The alert banner should scroll into view
1. Repeat for an invalid data file. Repeat for multiple files (multiple files, including combinations of valid and invalid should, just produce one banner)

## Deliverables
_More details on how deliverables herein are assessed included [here](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [x] Focus shifts to banner when Submit is clicked
+ [x] Banner is not in the normal tab order (i.e. you'll only be able to focus it in screenreader mode or by clicking submit)
+ [x] Testing Checklist has been run and all tests pass
+ [x] README is updated, if necessary
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [x] Does this PR complete the epic? 
+ [x] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [x] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by andrew-jameson — APPROVED** [review]

**Comment by andrew-jameson** [comment]
@reitermb @ADPennington Surely this needs a11y review?

**Review by n0remac — APPROVED** [review]

**Review by reitermb — APPROVED** [review]
Looking good as far as Raft a11y review goes! 

https://user-images.githubusercontent.com/28515874/199128958-8fc8b104-f19b-44db-a653-c71439e389c3.mp4

Scrolled the alert into a visible position & maintained existing aria-alert behavior. 👍

**Comment by ttran-hub** [comment]
> 

A11y 👍🚀

**Review by ADPennington — APPROVED** [review]
successfully tested that scroll to top works well after data submission. thanks @jtimpe 🚀  @andrew-jameson ready to merge

**Pull request merged**
