### PR TITLE
Security Control: SI-12

### PR DESCRIPTION
**Pull request by lfrohlich**
Adds security control implementation statement
Addresses issue #788

### CODE REVIEW

**Review by carltonsmith — APPROVED** [review]
LGTM!

**Comment by carltonsmith** [comment]
I moved the file to location we needed it to be in and updated the bullet points so they appear correctly in Markdown, but it looks good otherwise :)

**Comment by lfrohlich** [comment]
> I moved the file to location we needed it to be in and updated the bullet points so they appear correctly in Markdown, but it looks good otherwise. I'll wait for @kniz-raft to approve, and then I'll merge.

Thanks! Hold off on merging please until we get OCIO to review as well.

**Comment by lfrohlich** [comment]
@tdrammeh1 and @PenyinAsare, this is ready for your review.

**Review by ADPennington — COMMENTED** [review]
👍🏾 standing by for any feedback from @tdrammeh1 and @PenyinAsare

**Comment by PenyinAsare** [comment]
Approved

**Pull request merged**
