### PR TITLE
feat(1658): Make various models read-only through Django Admin

### LINKED ISSUE #1658: As a developer, I want to audit and update relevant fields available in DAC to be read-only
**Description:**
_Provide a brief background and justification for this issue_
We continue to stumble into fields we want to be read-only in DAC so I am proposing a holistic audit of all fields in DAC.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] The relevant objects are read-only for all user types through Django Admin
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Check every DAC page and determine if field should be read-only.
- [ ] Update permissions on relevant page::field combinations to be read-only in nature.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

### PR DESCRIPTION
**Pull request by jorgegonzalez**
## Summary of Changes

This PR adds a `ReadOnlyAdminMixin` utility that makes the Log Entries, Data Files, Clam AV File Scans, OWASP Zap Scans, Regions, and STT tables read-only for *all* user groups in Django Admin. Not that these objects can still be operated on through the API; these restrictions only apply to Django Admin.

Pull request closes #1658

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Navigate to Django Admin
1. Toggle-off the superuser flag for your user, if it is turned on 
1. Audit the Log Entries, Data Files, Clam AV File Scans, OWASP Zap Scans, Regions, and STT tables and ensure they are all read-only in the admin panel

> *Demo GIF(s) and screenshots for testing procedure*

## Tabletop

- [x] Ready for Tabletop (Reviewer check this)
- [x] Tabletop scheduled (Assignee check this)
- [x] Tabletop approval 

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] The relevant objects are read-only for all user types through Django Admin
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [x] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [x] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [x] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/raft-tdp-main/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by abottoms-coder — APPROVED** [review]
Works locally and this looks like it was done in the right Django-istic way. LGTM

**Review by riatzukiza — APPROVED** [review]

**Comment by abottoms-coder** [comment]
@ADPennington Why is this blocked? From reading the comments in 1282, it seems like that ticket should be blocked and not this one.

**Comment by ADPennington** [comment]
> @ADPennington Why is this blocked? From reading the comments in 1282, it seems like that ticket should be blocked and not this one.

@abottoms-coder i cannot test that the datafiles form fields are read-only on a deployed site because there are no files in the buckets. and i can't transmit a file to facilitate that test until #1699 is merged.

**Comment by ADPennington** [comment]
@jorgegonzalez still having some trouble submitting a datafile to confirm that the datafiles form fields are read-only. see below. (note: i tested on staging after data file bug merge and file transmission working fine there). could you look into this in another deployed site?  I'm going to release `raft` to @abottoms-coder

**Comment by abottoms-coder** [comment]
@ADPennington Can you mark your review as "requested changes" please?

**Review by ADPennington — CHANGES_REQUESTED** [review]
see [comment here](https://github.com/raft-tech/TANF-app/pull/1674#issuecomment-1086170204)

**Comment by ADPennington** [comment]
> > @jorgegonzalez still having some trouble submitting a datafile to confirm that the datafiles form fields are read-only. see below. (note: i tested on staging after data file bug merge and file transmission working fine there). could you look into this in another deployed site? I'm going to release `raft` to @abottoms-coder
> 
> @ADPennington This seems like an unrelated issue as this PR doesn't change any code related to submitting datafiles

redeploy fixed this issue.

**Pull request merged**
