### PR TITLE
Update Indicator Message

### LINKED ISSUE #3049: as an STT user, I need the error message related to the header update indicator clarified
**Description:**

As noted [here](https://github.com/raft-tech/TANF-app/pull/2963#issuecomment-2130178958), when #2963 merges, this will introduce an item number into the error message related to header update indicator, which is currently the most common error message that STTs receive. 

It looks like the following (when the update indicator is N, for example): `HEADER Item 10 (update indicator): N does not match D.`

- Header is not associated with an item number. 
- STTs also seem confused about the current error message in prod (when the update indicator is N, for example): `HEADER update indicator: N does not match D.`

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Error message for header update indicator does not include item number
- [ ] Error message for header update indicator matches language spec from UX team
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] UX team provides language spec for header update indicator error message
- [x] error message updated to include new language and remove item number
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- from @jtimpe: 

> the change is relatively easy:
  ```python=
Field(
    item="10",
    name="update",
    friendly_name="update indicator",
    type="string",
    startIndex=22,
    endIndex=23,
    required=True,
    validators=[validators.matches("D")],
),
```
> for our update indicator field, the `matches` validator can take a second argument `error_func`, similar to how `startsWith` works in the preparsing validators 
```python=
validators.startsWith(
    "HEADER",
    lambda value: f"Your file does not begin with a {value} record."
)
```
> that would let us hard code the message for the one specific case

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- #2818 
- #2963 

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- @reitermb @victoriaatraft can you provide guidance on the error message for the error message referenced in this ticket?

### PR DESCRIPTION
**Pull request by elipe17**
## Summary of Changes
- Added new error_func for header on the update indicator field
- Added coverage tests for header fields
Pull request closes #3049 

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose up
cd tdrs-backend && docker-compose up --build
```

1. Open http://localhost:3000/ and sign in
2. Submit a file with a bad update indicator
3. Verify the error report shows the latest error message for the indicator

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] Error message for header update indicator does not include item number
- [x] Error message for header update indicator matches language spec from UX team
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Comment by elipe17** [comment]
@reitermb, @victoriaatraft one thing I want to note is that any category two error on the header fields is going to lead to an error message of the form: `HEADER Item <ITEM_#> (<FRIENDLY_NAME>): <VALIDATOR_ERROR_MSG>`. Do we want to spin up follow on work to update those appropriately? Or, if we do want to fix the remaining field error messages, are you able to get the language to me by the end of the sprint so that I can update this PR? You can see examples of the messages without the placeholders if you look at the new test I added `test_header_fields` in `test_header.py` in the PR changed files.

cc @ADPennington

**Comment by elipe17** [comment]
> @reitermb, @victoriaatraft one thing I want to note is that any category two error on the header fields is going to lead to an error message of the form: `HEADER Item <ITEM_#> (<FRIENDLY_NAME>): <VALIDATOR_ERROR_MSG>`. Do we want to spin up follow on work to update those appropriately? Or, if we do want to fix the remaining field error messages, are you able to get the language to me by the end of the sprint so that I can update this PR? You can see examples of the messages without the placeholders if you look at the new test I added `test_header_fields` in `test_header.py` in the PR changed files.
> 
> cc @ADPennington

Discussed in stand up. Spinning up new ticket for remaining fields that should not have item number based error messages because they do not have item numbers.

**Review by andrew-jameson — APPROVED** [review]

**Review by raftmsohani — APPROVED** [review]
LGTM! Great work

**Review by victoriaatraft — APPROVED** [review]

**Review by reitermb — APPROVED** [review]
🚀

**Review by ADPennington — APPROVED** [review]
tested a few iterations by program type, section, and update indicator value. thank you @elipe17 @reitermb @victoriaatraft 🚀 
header_language

cc: @andrew-jameson this can wait until next week's release.

**Pull request merged**
