### PR TITLE
3023 whitelist ip

### LINKED ISSUE #3023: as STT approved user, I need my IP address whitelisted so i can access TDP
**Description:**

An approved user for a tribal program in Alaska was blocked from accessing the website. They shared the screenshot below after trying to get to the home page:

CCHITAforbidden

After reviewing the logs, it appears that the user was in a different location, and potentially on a mobile network (IPv6 is normally associated with mobile networks). The user did not confirm use of the mobile network but noted that they tried to access the system from a PC (this can be related to using wireless access point which grabs IPv6 instead IPv4 from the ISP). After discussion with dev, it was confirmed that this IP address is blocked, but does appear to be in the US. Therefore this should be whitelisted

CCHITAforbiddenlogs

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] The IP address referenced above is whitelisted, so user can access TDP. 
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Revise the whitelisted IP and add the IP range in question
- [ ] Run Testing Checklist and confirm all tests pass

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- One idea is to design dynamic nginx routing using local redis that is in sync with a backend DB for holding IP addresses. This is a bit advanced and might need more work

### PR DESCRIPTION
**Pull request by raftmsohani**
## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #3023 _

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] The IP address referenced above is whitelisted, so user can access TDP. 
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by elipe17 — APPROVED** [review]

**Comment by raftmsohani** [comment]
Tested on my phone (my phone had an ip address in the new ip range) and I could access. Tried prod, and I could not access.

**Comment by raftmsohani** [comment]
@ADPennington : Raft has the changes, if you have T-mobile then you should be able to test this. I did the test and it worked.

**Comment by ADPennington** [comment]
> Tested on my phone (my phone had an ip address in the new ip range) and I could access. Tried prod, and I could not access.

thank you! unfortunately we do not have the tools to test this. could you include the relevant logs in this PR @raftmsohani ?

**Review by jtimpe — APPROVED** [review]

**Comment by raftmsohani** [comment]
> > Tested on my phone (my phone had an ip address in the new ip range) and I could access. Tried prod, and I could not access.
> 
> thank you! unfortunately we do not have the tools to test this. could you include the relevant logs in this PR @raftmsohani ?

Here, first we try to login to qasp, which doesn't have the whitelisted IP:

Screenshot 2024-06-12 at 5 22 29 PM

As we can see, the ip address is blocked, now let's try RAFT which has the change:


Screenshot 2024-06-12 at 5 21 52 PM

**Review by ADPennington — APPROVED** [review]
thanks @raftmsohani lgtm 👍🏾

**Pull request merged**
