### PR TITLE
Feat/1906 use asterisk on access form

### LINKED ISSUE #1906: Change required form field convention to use asterisks on Request Access form
**Description:**
We're currently not providing any visual indication of "Associated STT" being required on the Request Access form. Since the form submits user data / can't easily be resubmitted we need a visual cue that it's required (as well as existing HTML attribute based identifiers that it's required). We've decided to use asterisks rather than "(required)" to make form field labels lest text heavy.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [x] Paragraph text exists above form to note "Fields marked with an asterisk (*) are required.''
- [x] Asterisks are present on all three fields making up Request Access 
- [x] Asterisks are within the label attribute
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
Deque guide to accessible identification of required fields https://dequeuniversity.com/tips/identify-required-elements

### PR DESCRIPTION
**Pull request by n0remac**
## Summary of Changes
Pull request closes #1906

## How to Test
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/.
2. Click sign in with gov cloud.
3. Make a new account and you will be redirected to the request access page.

Screen Shot 2022-07-07 at 11 40 46 AM

## Tabletop

- [x] Ready for Tabletop (Reviewer check this)
- [ ] Tabletop scheduled (Assignee check this)
- [x] Tabletop approval 

Checklist of ACs:
- [x] Paragraph text exists above form to note "Fields marked with an asterisk (*) are required.''
- [x] Asterisks are present on all three fields making up Request Access 
- [x] Asterisks are within the label attribute
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary

### [Deliverable 2: Tested Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [x] Does this PR complete the epic? 
+ [x] Are links included to any other gov-approved PRs associated with epic?
+ [x] Does PR include documentation for Raft's a11y review? 
+ [x] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [x] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](../docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by andrew-jameson — APPROVED** [review]

**Comment by ADPennington** [comment]
this looks good from a code review standpoint. @reitermb need evidence of your a11y review here. this is being deployed to qasp environment.  then please tag thomas and cc me  for `gov a11y review`.

**Review by reitermb — CHANGES_REQUESTED** [review]
https://user-images.githubusercontent.com/28515874/178064605-65960024-5ad2-498a-8937-bb0328df5d15.mov

Took a pass—asterisks are looking good and are appropriately read by VoiceOver, Narrator, and Talkback. Just one small thing I found, we're missing an ```aria-required="true"``` on the combobox input. I tested it in inspect and it achieved the intended effect of "required" being read by the screenreader after the label (matching the behavior for first/last name) so if that's added I think we should be good to send this on to QASP.

**Comment by reitermb** [comment]
cc: on the above @n0remac @ADPennington ☝️

**Comment by ADPennington** [comment]
@ttran-hub this is ready for `gov a11y review` . the page you will be doing a11y review is here: https://tdp-frontend-sandbox.app.cloud.gov/home and you will need to authenticate using non-acf credentials.

**Comment by ttran-hub** [comment]
@reitermb, can you check the mobile nav list items under MENU.  the Home read out as blank and none for email and sign out.
image

**Comment by reitermb** [comment]
> @reitermb, can you check the mobile nav list items under MENU. the Home read out as blank and none for email and sign out. image

I'm getting the correct behavior on my desktop web platforms (I'm stuck on the close button on Android—I wonder if whatever's causing that is related?). Attached a video of windows narrator but the behavior is the same for Safari / VoiceOver.

https://user-images.githubusercontent.com/28515874/179316819-4e104ced-6ed0-4c4e-8dee-a2a70780b5ed.mp4

**Comment by stevenino** [comment]
@ttran-hub @ADPennington back to QASP

**Comment by ADPennington** [comment]
> @ttran-hub @ADPennington back to QASP

@ttran-hub can you connect with @reitermb on this one to discuss the difference in the behavior you all are seeing?

**Comment by ADPennington** [comment]
> > @ttran-hub @ADPennington back to QASP
> 
> @ttran-hub can you connect with @reitermb on this one to discuss the difference in the behavior you all are seeing?

@reitermb @stevenino Thomas is out sick today. I've added the `blocked` label until he's returned. also removing the a11y deployment tag to free it up in the meantime.

**Comment by ADPennington** [comment]
> please check: Backend.sandbox is getting the below error after login https://tdp-frontend-sandbox.app.cloud.gov/home image

@ttran-hub i just deployed this to [qasp environment](https://tdp-frontend-qasp.app.cloud.gov/home). Please feel free to test there when all the checks are green. Also note you'll need to authenticate using non-ACF credentials. please ping me if you need access to the request form (we may need to delete your pre-existing user). 

cc: @n0remac

**Comment by ADPennington** [comment]
the re-deploy didnt resolve whatever is going on in the user model. captured devtools evidence below. will need to spin up a ticket if we see this in staging after this is approved and merged, since this is beyond scope of this ticket cc: @n0remac 

_raft_
Screen Shot 2022-07-20 at 12 38 36 PM


_qasp_

Screen Shot 2022-07-20 at 12 43 44 PM

**Comment by n0remac** [comment]
Is there any action needed from me on this?

**Comment by ttran-hub** [comment]
> > @reitermb, can you check the mobile nav list items under MENU. the Home read out as blank and none for email and sign out. image
> 
> I'm getting the correct behavior on my desktop web platforms (I'm stuck on the close button on Android—I wonder if whatever's causing that is related?). Attached a video of windows narrator but the behavior is the same for Safari / VoiceOver.
> 
>  chrome_QlAe85N6na.mp4 
> Happy to pair on this next week if there's some troubleshooting we might want to do here.

image
Getting the same read out from Firefox and Chrome, @reitermb let pair on this.

**Comment by stevenino** [comment]
Might be worth pulling in @n0remac as well.

**Comment by ttran-hub** [comment]
review: [qasp environment](https://tdp-frontend-qasp.app.cloud.gov/home).
@reitermb will spin out a ticket for additional review of the mobile submenu.
First and Last Name * (require) readout ✔️
The "Associated State, Tribe, or Territory" is missing the "Required" readout

**Comment by reitermb** [comment]
> review: [qasp environment](https://tdp-frontend-qasp.app.cloud.gov/home). @reitermb will spin out a ticket for additional review of the mobile submenu. First and Last Name * (require) readout ✔️ The "Associated State, Tribe, or Territory" is missing the "Required" readout

Adding some commentary: 
I'm refining #1984 (cc: @stevenino) to be that fix for whatever happened to the menu—we're not sure what's going on but did at least identify that whatever it is was introduced in a different ticket, so we won't make fixing it part of the scope of this one.

I'm pretty sure I remember you (@n0remac) adding an aria-required to the STT field at one point, is it possible we just lost that commit somewhere along the way?

**Review by reitermb — APPROVED** [review]
Perfect! 🚀 

Confirming that Cameron got the ```aria-required="true"``` property onto the part of the combobox that gets read by screenreaders (the input, as opposed to the select or the overall div). I've also screenreader tested it and confirmed the behavior is working!



As per the sync I had with Thomas yesterday this should now be complete. cc @ttran-hub @ADPennington

**Comment by ttran-hub** [comment]
> Perfect! 🚀
> 
> Confirming that Cameron got the `aria-required="true"` property onto the part of the combobox that gets read by screenreaders (the input, as opposed to the select or the overall div). I've also screenreader tested it and confirmed the behavior is working!
> 
> image
> 
> As per the sync I had with Thomas yesterday this should now be complete. cc @ttran-hub @ADPennington

Awesome, looking good! thanks @n0remac and @reitermb! 🚀

**Review by ADPennington — APPROVED** [review]
approved per @ttran-hub's [gov a11y review](https://github.com/raft-tech/TANF-app/pull/1937#issuecomment-1194423577) 👍🏾

**Pull request merged**
