### PR TITLE
Create ac-2(10).md

### PR DESCRIPTION
**Pull request by rnafarrete**
### This pull request changes...

Implementation statement for ac-2(10)

### This pull request is ready to merge when...

- [ ] Meets acceptance criteria for the issue 
- [ ] Code is reviewed by someone other than the original author
- [ ] Code is tested 
- [ ] Experience is approved by UX  
- [ ] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [ ] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [ ] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

### CODE REVIEW

**Review by carltonsmith — APPROVED** [review]
LGTM

**Comment by carltonsmith** [comment]
@lfrohlich @hursey013 Waiting to put this PR into QASP until the remaining security control PRs have been approved and merged

**Comment by hursey013** [comment]
Looks great! @lfrohlich pending any feedback you have, I believe this is ready for OCIO review!

**Review by ADPennington — COMMENTED** [review]
@tdrammeh1 and  @PenyinAsare this is ready for your review.

**Comment by tdrammeh1** [comment]
Reviewed and approved.

**Review by ADPennington — APPROVED** [review]
approved per: https://github.com/raft-tech/TANF-app/pull/677#issuecomment-791639966

**Pull request merged**
