### PR TITLE
Documentation/access controls ac 17

### PR DESCRIPTION
**Pull request by rnafarrete**
### This pull request changes...

Updated implementation statement for AC-17

### This pull request is ready to merge when...

- [ ] Meets acceptance criteria for the issue 
- [ ] Code is reviewed by someone other than the original author
- [ ] Code is tested 
- [ ] Experience is approved by UX  
- [ ] Meets [a11y checklist](https://github.com/HHS/TANF-app/blob/main/docs/a11y/how-18f-will-test-a11y.md)
- [ ] Meets [Raft's Manual QASP Checklist](https://teams.microsoft.com/l/file/B5285301-13CA-46FD-A723-AFFD578C224A?tenantId=d58addea-5053-4a80-8499-ba4d944910df&fileType=docx&objectUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA%2FShared%20Documents%2FGeneral%2FManual%20Testing%20Practices_Issue173.docx&baseUrl=https%3A%2F%2Fhhsgov.sharepoint.com%2Fsites%2FTANFDataPortalOFA&serviceName=teams&threadId=19:f769bbcb029f4f02b55ae7fad90e310d@thread.skype&groupId=41f194a6-c1d3-4680-933e-c8ee7d17e287):lock: (only applicable for PR to main HHS)
- [ ] Documentation is updated 
  - OpenAPI  
  - Readme
  - Entity Relationship Diagram (ERD)

### CODE REVIEW

**Comment by carltonsmith** [comment]
The comments above indicate that this is a draft. I assume it's no longer a draft since you assigned it to me. Can you please update that @rnafarrete?

**Comment by rnafarrete** [comment]
Updated - removed draft label in pull request.

**Review by carltonsmith — APPROVED** [review]
LGTM

**Comment by hursey013** [comment]
@carltonsmith I noticed that AC-17 isn't on the CRM - do we know where this originated from?

**Comment by carltonsmith** [comment]
> @carltonsmith I noticed that AC-17 isn't on the CRM - do we know where this originated from?

Just part of the work Romelo put in. I can delete it if it's not needed

**Comment by kniz-raft** [comment]
> > @carltonsmith I noticed that AC-17 isn't on the CRM - do we know where this originated from?
> 
> Just part of the work Romelo put in. I can delete it if it's not needed

I vote we close this PR and the issue at this time in order to prioritize the ones needed for the CRM.

**Comment by hursey013** [comment]
@kniz-raft agreed - let's close for now 👍

**Comment by carltonsmith** [comment]
Closing as per notes above

**Pull request closed without merging**
