### PR TITLE
1532 - Hero image swap

### LINKED ISSUE #1532: Update hero images
**Description:**
Update hero images with new widened versions from #1346 .

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] Splash page for unauthenticated users displays use images from [these mockups](https://reitermb.github.io/TDP-Project-Update/)
- [ ] Images are not cut off by button text box
- [ ] No other frontend settings should be changed
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Update hero images used to those linked below.
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 
- Please see [last time we updated them](https://github.com/raft-tech/TANF-app/pull/1383/files) for a reference.

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Hero image 1](https://github.com/reitermb/TDP-Project-Update/blob/main/img/HI1.jpg)
- [Hero image 2](https://github.com/reitermb/TDP-Project-Update/blob/main/img/HI2.jpg)
- [Hero image 3](https://github.com/reitermb/TDP-Project-Update/blob/main/img/HI3.jpg)

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_

### PR DESCRIPTION
**Pull request by andrew-jameson**
## Summary of Changes
Pull request closes #1532

### CODE REVIEW

**Comment by andrew-jameson** [comment]
@reitermb @ADPennington Do we want this deployed to ally just to check?

**Comment by ADPennington** [comment]
> @reitermb @ADPennington Do we want this deployed to ally just to check?

yes please

**Review by reitermb — APPROVED** [review]
Looking good—and should all be clear on a11y given that there's no text against our backgrounds and they're decorative images. 

https://user-images.githubusercontent.com/28515874/217368522-1d62f7ef-852d-4812-b07a-2432bd0317e3.mp4

**Review by ADPennington — APPROVED** [review]
lgtm! cc: @lfrohlich @ttran-hub 
before:
hero2

after:
hero1

**Pull request merged**
