### PR TITLE
Security Controls: IA-08

### PR DESCRIPTION
**Pull request by kniz-raft**
### Summary of Changes
_Adds implementation statement_
_Addresses issue #712 _

### CODE REVIEW

**Review by carltonsmith — APPROVED** [review]
LGTM

**Review by alexsoble — APPROVED** [review]
@tdrammeh1 and @PenyinAsare, this is ready for your review.

**Comment by PenyinAsare** [comment]
I might be missing something or I still don't know how to navigate github … but where exactly is the implementation statement??

**Comment by carltonsmith** [comment]
> I might be missing something or I still don't know how to navigate github … but where exactly is the implementation statement??

No problem @PenyinAsare - if you look at the top of the page you will see a link that says "Files Changed"
files_changed

**Comment by PenyinAsare** [comment]
Thanks @carltonsmith

**Comment by PenyinAsare** [comment]
Statement Approved

**Pull request merged**
