### PR TITLE
2618 nginx config site down

### LINKED ISSUE #2618: Down for maintenance page
**Description:**
Create a static page and have nginx render this for all routes if a env var is set to True

Old ticket: #2066

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] STRETCH: include same headers/footers as in the 404 error
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] Implement nginx location based on environment variable
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

### PR DESCRIPTION
**Pull request by raftmsohani**
## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #2618

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

to enable site maintenance page:
1. ssh into the frontend instance using ``` cf ssh XYZ```
2.
```
cd ~/app/public
mv 503_.html 503.html
```

This PR is currently deployed to RAFT. (Jul 30th)

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] STRETCH: include same headers/footers as in the 404 error
- [x] Testing Checklist has been run and all tests pass
- [x] README is updated, if necessary
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [x] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [x] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Comment by andrew-jameson** [comment]
Before:
Screenshot 2023-07-31 at 9 34 21 AM

One nit-pick here -- we have javascript logic for the banner "Dev Demo website..." -- b/c it's just static html, we can't render this. I don't want to have to overinvest in this, are we fine with moving forward as-is @ADPennington ?

```
andrewjameson@Andrews-MacBook-Pro puzzles % cf ssh tdp-frontend-raft
vcap@***~$ cd app/public
vcap@***:~/app/public$ mv 503.html 503_.html
```

After:
image

**Review by andrew-jameson — APPROVED** [review]

**Comment by reitermb** [comment]
image

A11y is looking good—noting that we're adding a hardcoded production version of the banner and that will add working expandability to the banner / possibly necessitate a quick a11y re-test but I expect that'll sail right through the tests too.

cc @ADPennington @ttran-hub

**Comment by reitermb** [comment]
Committed the banner changes. I used the full (though minified) uswds javascript we have in the knowledge center to get the banner expansion working which I'm sure is overkill, but I'm not sure offhand how to isolate the functions in there that handle it. 

Also added a skip link and simplified the HTML around the contact us button (there was an unnecessary list element). 

All changes still in the clear a11y wise and playing nicely with screenreaders. 

image
image
image
image




cc @ADPennington @andrew-jameson @raftmsohani @ttran-hub

**Comment by raftmsohani** [comment]
> Before: Screenshot 2023-07-31 at 9 34 21 AM
> 
> One nit-pick here -- we have javascript logic for the banner "Dev Demo website..." -- b/c it's just static html, we can't render this. I don't want to have to overinvest in this, are we fine with moving forward as-is @ADPennington ?
> 
> ```
> andrewjameson@Andrews-MacBook-Pro puzzles % cf ssh tdp-frontend-raft
> vcap@***~$ cd app/public
> vcap@***:~/app/public$ mv 503.html 503_.html
> ```
> 
> After: image

Just a note: For now we can only show static page with embedded CSS and JS.

**Review by ADPennington — APPROVED** [review]
lgtm! thanks @raftmsohani @reitermb 

before:
maint1

after:
maint2

---

commands 

```
# login
cf login -a api.fr.cloud.gov  --sso 

# target environment
cf target -o hhs-acf-ofa -s tanf-dev

# get process guid for frontend app
cf curl v3/apps/$(cf app tdp-frontend-qasp --guid)/processes | jq --raw-output '.resources | .[]? | select(.type == "web").guid'

# get ssh code
cf ssh-code

# ssh into app
ssh -p 2222 cf:<process guid>/0@ssh.fr.cloud.gov  
<insert ssh-code when prompted>

# set maintenance page in front of splash page then exit
cd ~/app/public
mv 503_.html 503.html
exit

# restart app when done with maintenance
cf restart tdp-frontend-qasp

```

**Pull request merged**
