### PR TITLE
3.5.2 release notes

### PR DESCRIPTION
**Pull request by reitermb**
## Summary of Changes
Delivers HTML updates for #3143 

Testable at:
https://reitermb.github.io/Test/knowledge-center/

### CODE REVIEW

**Comment by ADPennington** [comment]
thanks @reitermb. appreciate the quick turnaround on this. Please note:

- I've made some in-line edits to the gitbooks version. 
- Do you have recommendations on the process we should follow to get the email template version of this? Would it be shortly after this merges? 
cc: @lfrohlich @ttran-hub

**Comment by reitermb** [comment]
> thanks @reitermb. appreciate the quick turnaround on this. Please note:
> 
> * I've made some in-line edits to the gitbooks version.
> * Do you have recommendations on the process we should follow to get the email template version of this? Would it be shortly after this merges?
>   cc: @lfrohlich @ttran-hub

Content added! 

image


Given how lightweight our email approach is currently, it's really just a question of copying and pasting content from either Gitbooks or the PR into an email and inserting links in the appropriate spots. We're happy to deliver the first draft of that but it's nothing that requires direct manipulation of our email templates or knowledge center environments.

**Comment by reitermb** [comment]
A11y scan: 
image

**Comment by ADPennington** [comment]
@reitermb I took another pass, mostly to revise some of my original edits. Please note:

- I raised a question about feasibility to guide users more directly to the header-related content on another page, like [this](https://tdp-project-updates.app.cloud.gov/knowledge-center/viewing-error-reports.html#:~:text=4%20(Stratum%20Data)-,Header%20and%20Trailer%20Records,-The%20Header%20and)

- i made a minor suggestion to point folks to the feedback page to continue helping us collect their feedback

please ping us when we can take a look at this in the test environment. cc: @ttran-hub @lfrohlich

**Review by ADPennington — CHANGES_REQUESTED** [review]
Changes requested per comments.

**Comment by reitermb** [comment]
Changes (all live in the test environment): 
-  Content reflecting latest GitBook version 
- Accessible skip-to-header section on the error report explainer (screenreader tested; readout works as expected)

chrome_pCwlxW7rQv

chrome_xTlgYk4F65

image

@ADPennington @ttran-hub @lfrohlich

**Review by ADPennington — APPROVED** [review]
the OFA team appreciates this high-pri turnaround from the UX team. Let's discuss how to refine this process going forward at next ux sync. 

Ready to merge! 🚀 cc: @lfrohlich @ttran-hub

**Pull request merged**
