### PR TITLE
3180 - error type field

### LINKED ISSUE #3180: Re-add Error Type column to Error Reports
**Description:**
We plan to help certain STTs encountering a high volume of errors by leveraging error type as a way to direct their attention toward the highest priority issues first as a more tackle-able subset of error corrections. Not blocked by but relates to #3181 

**Acceptance Criteria:** 
- [ ] (friendly version) Error Type column appears in error reports
- [ ] Error type column appears as the right-most column
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] Adjust error report generation to include error type column (friendly name error category version, not a numeric)
- [ ] Run Testing Checklist and confirm all tests pass

### PR DESCRIPTION
**Pull request by jtimpe**
## Summary of Changes
Pull request closes #3180
* Adds the "error type" column back to the generated error report, this time with the "friendly" label instead of the numeric value

## How to Test
```
cd tdrs-backend && docker compose up
cd tdrs-frontend && docker compose up --build
```

1. Open http://localhost:3000/ and sign in.
1. Download an error report. Examine the "error type" column for each error in the report

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [x] (friendly version) Error Type column appears in error reports
+ [x] Error type column appears as the right-most column
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by raftmsohani — APPROVED** [review]
LGTM!

**Review by elipe17 — APPROVED** [review]
LGTM

**Review by andrew-jameson — APPROVED** [review]

**Comment by ADPennington** [comment]
this is in great shape @jtimpe 🥇 -- approval coming up tomorrow. I'd just like to firm up [release note next steps](https://github.com/raft-tech/TANF-app/issues/3180#issuecomment-2384169375) with UX team at our sync tmor morning before this closes.

**Review by ADPennington — APPROVED** [review]
appreciate the quick change @jtimpe 👍🏾 

- Evidence of the updated error report is [here](https://github.com/raft-tech/TANF-app/issues/3180#issuecomment-2384169375)
- Really nice to see that this change applies to new and previously-generated error reports, so resubmission or reparsing command isn't needed to  access the error type. 
- I'm hopeful that the release notes, KC guidance, and UX research can help inform if the error type "friendly names" are easy-to-understand. As is, I think we should expect clarifying questions, which is 🆗 for now. cc: @klinkoberstar @ttran-hub @victoriaatraft @reitermb

**Pull request merged**
