### PR TITLE
Update communication-tools.md

### PR DESCRIPTION
**Pull request by valcollignon**
### Summary of Changes
Updating Team Charter > Our Team Communication Tools

### CODE REVIEW

**Comment by ADPennington** [comment]
@valcollignon can you check if your changes here are reflected in #1501 and if so, can you close this one?

**Comment by valcollignon** [comment]
@ADPennington the changes here are different from the changes in #1501. They both need to be merged, I think.

**Comment by abottoms-coder** [comment]
> @ADPennington the changes here are different from the changes in #1501. They both need to be merged, I think.

So this is in QASP pending @lfrohlich's approval and the "Ready to merge label"?

**Review by lfrohlich — APPROVED** [review]
Looks great, thanks!

**Pull request merged**
