### PR TITLE
[Snyk] Upgrade react-idle-timer from 4.5.0 to 4.5.1

### PR DESCRIPTION
**Pull request by carltonsmith**
<h3>Snyk has created this PR to upgrade react-idle-timer from 4.5.0 to 4.5.1.</h3>

merge advice
:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **1 version** ahead of your current version.
- The recommended version was released **22 days ago**, on 2021-01-08.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>react-idle-timer</b></summary>
    <ul>
      <li>
        <b>4.5.1</b> - <a href="https://snyk.io/redirect/github/SupremeTechnopriest/react-idle-timer/releases/tag/4.5.1">2021-01-08</a></br><h2><g-emoji class="g-emoji" alias="sparkles" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2728.png">✨</g-emoji> Enhancements</h2>
<ul>
<li>Added the ability to set <code>timeout</code> dynamically in the useIdleTimer hook.  Doing so will automatically reset the timer if it is active.</li>
</ul>
      </li>
      <li>
        <b>4.5.0</b> - <a href="https://snyk.io/redirect/github/SupremeTechnopriest/react-idle-timer/releases/tag/4.5.0">2020-10-30</a></br><h2><g-emoji class="g-emoji" alias="zap" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/26a1.png">⚡️</g-emoji> Features</h2>
<ul>
<li>Added  <code>getLastIdleTime</code> and <code>getTotalIdleTime</code> methods.</li>
</ul>
<h2><g-emoji class="g-emoji" alias="sparkles" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2728.png">✨</g-emoji> Chores</h2>
<ul>
<li>Refactor <code>getTotalActiveTime</code> to be accurate in more scenarios.</li>
<li>Switched from Travis CI to Github Actions.</li>
</ul>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/supremetechnopriest/react-idle-timer/releases">react-idle-timer GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>react-idle-timer</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/SupremeTechnopriest/react-idle-timer/commit/ea7fbd03142dcb067beb73d58df2263324074130">ea7fbd0</a> 📦 4.5.1</li>
      <li><a href="https://snyk.io/redirect/github/SupremeTechnopriest/react-idle-timer/commit/fee331a1d5a07db50963b8e425e92b88bddb7765">fee331a</a> 📦 4.5.1</li>
      <li><a href="https://snyk.io/redirect/github/SupremeTechnopriest/react-idle-timer/commit/983cf1c6b8c76ca30a1ebd8f996eba4eca355c15">983cf1c</a> 🐞 Allow dynamic timeout property (#135 &amp; #137).</li>
    </ul>

   <a href="https://snyk.io/redirect/github/SupremeTechnopriest/react-idle-timer/compare/7ff40e649770654ca35325388c86f021e2dd74b2...ea7fbd03142dcb067beb73d58df2263324074130">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/raftergit/project/f394fdd3-a51a-4643-a79f-e9c30e52758d?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/raftergit/project/f394fdd3-a51a-4643-a79f-e9c30e52758d/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/raftergit/project/f394fdd3-a51a-4643-a79f-e9c30e52758d/settings/integration?pkg&#x3D;react-idle-timer&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Comment by carltonsmith** [comment]
@jorgegonzalez or @jtwillis92 Can one of you please review this PR? We need to make sure there aren't any breaking changes before we can put in a PR to HHS

**Comment by jorgegonzalez** [comment]
[Several releases](https://github.com/supremetechnopriest/react-idle-timer/releases) for `react-idle-timer` have been made since this PR was opened by snyk, the latest being `v4.5.5`. Would we want to continue with the update in this PR or have snyk go further?

**Comment by carltonsmith** [comment]
> [Several releases](https://github.com/supremetechnopriest/react-idle-timer/releases) for `react-idle-timer` have been made since this PR was opened by snyk, the latest being `v4.5.5`. Would we want to continue with the update in this PR or have snyk go further?

I think it would make sense to try to upgrade it to the latest version and test it that way

**Comment by jtwillis92** [comment]
I agree, looks like the version currently proposed for upgrade adds a new feature to the `useIdleTimer` hook (that we currently use) and the subsequent versions fix some bugs in that implementation. Would be good to get to the latest version so we can possibly leverage that feature in the future and not run into bugs that are already fixed.

**Comment by carltonsmith** [comment]
Closing this and creating a new issue to upgrade to the latest

**Pull request closed without merging**
