### PR TITLE
Security Controls SC-20

### PR DESCRIPTION
**Pull request by carltonsmith**
### Summary of Changes

Security control documentation for SC-20

### CODE REVIEW

**Comment by lfrohlich** [comment]
From @penyinasare this is DNS, so would be cloud.gov

**Comment by kniz-raft** [comment]
@carltonsmith for this one, do we need to just change the language in the control to be cloud.gov instead of login.gov?

**Comment by alexsoble** [comment]
(Covering for @ADPennington on QASP review for a bit!)

**Review by alexsoble — APPROVED** [review]
@tdrammeh1 and @PenyinAsare, this is ready for your review.

**Comment by PenyinAsare** [comment]
Approved

**Pull request merged**
