### PR TITLE
updating to latest zapscanner container version (2.13.0) and removed …

### LINKED ISSUE #2644: [spike] Investigate nightly OWASP scan failure
**Description:**
Sprint 77 release is in `HHS/TANF-app:main` and the result of the nightly scan is below. 
nightlymain

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [ ] _Task 1_
- [ ] _Task 2_
- [ ] _Task 3_
- [ ] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

### PR DESCRIPTION
**Pull request by George-Hudson**
## Summary of Changes
This change removed our Scan endpoint from the global exclude list, which was causing nightly scans to fail. 
Pull request closes #2644

## How to Test
created a branch just to test on circleci and ran "nightly" scans by triggering a run with the boolean parameter run_nightly_owasp_scan set to true. https://app.circleci.com/pipelines/github/raft-tech/TANF-app/15244/workflows/77e65bb0-ade1-4af7-af49-6b3140e9eda7/jobs/45620

Checklist of ACs:
+ [ ] [once in develop, nightly scans run to completion]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Comment by George-Hudson** [comment]
@raftmsohani do we need to create something to replace:
```
  -config globalexcludeurl.url_list.url\(3\).regex='^https:\/\/.*\.hhs.gov\/.*$' \
  -config globalexcludeurl.url_list.url\(3\).description='Site - acf.hhs.gov' \
  -config globalexcludeurl.url_list.url\(3\).enabled=true \
```
but that doesn't enclude our endpoint? I don't know the original intent of having this a part of the global exclude list.

**Review by andrew-jameson — APPROVED** [review]
Glad we caught it, although the actual ZAP artifacts show we have high and medium vulns to address.

**Review by jtimpe — APPROVED** [review]

**Review by raftmsohani — APPROVED** [review]

**Comment by ADPennington** [comment]
@George-Hudson @andrew-jameson @raftmsohani @jtimpe @Smithh-Co if no further changes to this PR, we'll need a follow-on ticket to determine which of these findings are/arent false positives and how to exclude false positives. 

26644p2
26644p1

**Comment by andrew-jameson** [comment]
> @George-Hudson @andrew-jameson @raftmsohani @jtimpe @Smithh-Co if no further changes to this PR, we'll need a follow-on ticket to determine which of these findings are/arent false positives and how to exclude false positives.
> 
> 26644p2 26644p1

I believe the medium vuln around the 403 bypass is bogus because we saw this before and/or with 401. On the CORS misconfig front, we'll have to check it.

**Pull request merged**
