### PR TITLE
3109 - Quarter Explainer

### LINKED ISSUE #3109: Light-Lift Fiscal Quarter and Calendar Quarter Explainer in TDP
**Description:**
Follow on dev ticket to design ticket #3057 and related to #3017

Release Notes:
- Table added to Data Files Page
- Explain difference between fiscal and calendar year in plain language
- Note when the government fiscal year starts

**Acceptance Criteria:** 
- [x]  Data Files page matches mockup found below
- [x]  Internal Raft Review has occurred to ensure DoD standards and QA
- [x]  The design is usable and accessible, meaning it adheres to definition of done standards for design work.
- [x] Table is responsive on narrow/mobile screen devices and a11y accessible

**Tasks:**
- [x] Add "Fiscal" to label in Data Files
- [x] Add table created in mockups to Data Files page within a two column format
- [ ] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**

- [Figma Mockups](https://www.figma.com/design/irgQPLTrajxCXNiYBTEnMV/TDP-Mockups-For-Feedback?node-id=8902-3268)
- [Ideation Mural](https://app.mural.co/t/raft2792/m/raft2792/1718739423199/ed42a2fa979a5d63876ab96bd9399458f390f725?sender=uf443e00cb4626b8bec157528)

image

### PR DESCRIPTION
**Pull request by jtimpe**
## Summary of Changes
Pull request closes #3109 
* adds the fiscal-quarter/calendar-quarter explanation table to Reports.jsx

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-backend && docker-compose up
cd tdrs-frontend && docker-compose up --build
```

1. Open http://localhost:3000/ and sign in.
1. Navigate to the Data Files page. Examine the explainer table.

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [x] Data Files page matches mockup found below
+ [x] Internal Raft Review has occurred to ensure DoD standards and QA
+ [x] The design is usable and accessible, meaning it adheres to definition of done standards for design work.
+ [x] Table is responsive on narrow/mobile screen devices and a11y accessible
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [x] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [x] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by andrew-jameson — APPROVED** [review]

**Comment by reitermb** [comment]
image

Manual and auto testing all good on the a11y side. Just pending a couple small style tweaks, should be good to go once implemented.

**Review by raftmsohani — APPROVED** [review]

**Review by elipe17 — APPROVED** [review]

**Review by victoriaatraft — APPROVED** [review]
Screenshot 2024-10-15 at 12 23 36 PM

LGTM from an a11y perspective. I do want to comment that the white space between both looks uncomfortably and visually off with that much white space. 

I would suggest closing the gap to where they look grouped together (perhaps the same amount of space that is between the first column and the edge of the left side of the page or similar). I would also consider moving the table up to align with the Associated State, Tribe, Territory because it is technically perceived as two columns. 

cc @reitermb for any accessibility concerns and @ADPennington for awareness

**Comment by ADPennington** [comment]
> Screenshot 2024-10-15 at 12 23 36 PM
> LGTM from an a11y perspective. I do want to comment that the white space between both looks uncomfortably and visually off with that much white space.
> 
> I would suggest closing the gap to where they look grouped together (perhaps the same amount of space that is between the first column and the edge of the left side of the page or similar). I would also consider moving the table up to align with the Associated State, Tribe, Territory because it is technically perceived as two columns.
> 
> cc @reitermb for any accessibility concerns and @ADPennington for awareness

per standup today, @jtimpe will investigate table spacing based on @victoriaatraft's feedback. shouldn't block QASP review.

**Review by ADPennington — APPROVED** [review]
@jtimpe i agree with @victoriaatraft that there is a lot white space between the combo-boxes and the table, but otherwise this LGTM! cc: @ttran-hub @klinkoberstar 

some artifacts below, by page width and permission group 

_narrow page_
narrow_view

_data analyst_
data_analyst_page

_digit_
digit_page

_sys admin_
sys_page

**Comment by jtimpe** [comment]
Most recent changes to handle whitespace results in the following

Desktop: 
image

Mobile:
image

**Comment by ADPennington** [comment]
@jtimpe @victoriaatraft @ttran-hub i checked this out in the raft env and this change lgtm too!

Screenshot 2024-10-17 135913

**Comment by jtimpe** [comment]
@ADPennington and @reitermb i want to make you aware of one more of @victoriaatraft's suggestions that i wasn't able to implement

> I would also consider moving the table up to align with the Associated State, Tribe, Territory because it is technically perceived as two columns.

i would've liked to do this, but in the case that the Associated State/Tribe/Territory and File Type inputs are both not visible, the grid kinda falls apart

image

i'd fix that by re-designing the grid layout but felt that was too big of change here since it wasn't originally asked for in the ticket. i also have more questions/comments about the form from the technical perspective and would like to bring those things up in conversation together.

**Pull request merged**
