### PR TITLE
3113 added validation skip error

### LINKED ISSUE #3113: As tech lead, I need the validation on the header update indicator revised to unblock parsing
**Description:**

The validation on the header update indicator was introduced to help enforce OFA's expectation that STTs would submit all records with every submission. Because this validation check was recently implemented, most files submitted via TDP do not have the appropriate update indicator value, and the re-parsing command introduced in #3041 cannot be used to re-process these files unless this value is correct. 

Since manual correction and resubmission of these files is not feasible for OFA or STTs, the validator needs to be relaxed. 

**Acceptance Criteria:** 

- [x] Validator for header update indicator revised such that records can still be processed when the update indicator value is not `D`
- [x] An error message related to header update indicator is still included in the error report when the value is not `D`
- [x] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] update header update indicator validator
- [x] Run Testing Checklist and confirm all tests pass

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- [Manual resubmission results](https://gorafttech.sharepoint.com/sites/TDRSResearchDesign/_layouts/15/Doc.aspx?sourcedoc={c9d41a72-bff8-4eba-b245-bb04ba265e12}&action=edit&wd=target%28Dev%20Notes.one%7C567fc274-f86b-0a48-901d-543bdc5250ac%2FManual%20Resubmission%20Results%7C3ff147be-7c9a-4ef3-90cd-9e37e32407a5%2F%29&wdorigin=NavigationUrl)

### PR DESCRIPTION
**Pull request by raftmsohani**
## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #3113 _

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d
cd tdrs-backend && docker-compose -f docker-compose.yml -f docker-compose.local.yml up -d 
```

1. Open http://localhost:3000/ and sign in.
1. Proceed with functional tests as described herein.
1. Test steps should be captured in the demo GIF(s) and/or screenshots below.
> *Demo GIF(s) and screenshots for testing procedure*

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] Validator for header update indicator revised such that records can still be processed when the update indicator value is not `D`
- [x] An error message related to header update indicator is still included in the error report when the value is not `D`
+ [x] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by jtimpe — APPROVED** [review]
Approving because it solves the ticket AC and is a fairly minimal change, but I'd like to raise one point of discussion.

This feels a little hacky to me because we're adding a feature to `Field`, used all over the place, only to use it once to effectively work around the design choice that all header field errors should short-circuit parsing. I don't see the `ignore_errors` flag being useful otherwise (though I'm open to that possibility). To me, we should solve this more in the direction of "some header errors stop the parsing workflow" (i.e., error precedence) rather than "all header errors stop parsing except for some".

Not asking for any changes from you here, but I do think this is something we should consider as we continue to think about optimizing the parser structure.

**Comment by raftmsohani** [comment]
> Approving because it solves the ticket AC and is a fairly minimal change, but I'd like to raise one point of discussion.
> 
> This feels a little hacky to me because we're adding a feature to `Field`, used all over the place, only to use it once to effectively work around the design choice that all header field errors should short-circuit parsing. I don't see the `ignore_errors` flag being useful otherwise (though I'm open to that possibility). To me, we should solve this more in the direction of "some header errors stop the parsing workflow" (i.e., error precedence) rather than "all header errors stop parsing except for some".
> 
> Not asking for any changes from you here, but I do think this is something we should consider as we continue to think about optimizing the parser structure.

@jtimpe Since the AC is an edge case, the solution would be hacky in anycase. I first added a conditional error in parse file but I decided not to add more to that file, and changed it to a field setting. To me, this will be much cleaner to remove.

**Comment by raftmsohani** [comment]
> > Approving because it solves the ticket AC and is a fairly minimal change, but I'd like to raise one point of discussion.
> > This feels a little hacky to me because we're adding a feature to `Field`, used all over the place, only to use it once to effectively work around the design choice that all header field errors should short-circuit parsing. I don't see the `ignore_errors` flag being useful otherwise (though I'm open to that possibility). To me, we should solve this more in the direction of "some header errors stop the parsing workflow" (i.e., error precedence) rather than "all header errors stop parsing except for some".
> > Not asking for any changes from you here, but I do think this is something we should consider as we continue to think about optimizing the parser structure.
> 
> @jtimpe Since the AC is an edge case, the solution would be hacky in anycase. I first added a conditional error in parse file but I decided not to add more to that file, and changed it to a field setting. To me, this will be much cleaner to remove.

Another solution might be a decorator just to bypass the error generation. I will take a look at that solution make it cleaner

**Review by andrew-jameson — APPROVED** [review]
Covered in office hours

**Review by elipe17 — APPROVED** [review]

**Review by ADPennington — APPROVED** [review]
lgtm! thanks @raftmsohani 🚀 

Confirmed the following:

- update indicator value no longer blocks parsing for TANF, SSP, and Tribal TANF Files
- error message for out-of-range update indicator value still raised when applicable.

**Pull request merged**
