### PR TITLE
Alertmanager Cloud.gov

### LINKED ISSUE #3254: Alertmanger Cloud.gov
**Description:**
As a follow on to #3242, Alertmanager (AM) will need to be deployed to the production environment in cloud.gov with the rest of PLG. Pending the merge status of #3046 the implementer may be inclined to silence certain alerts from AM to avoid false positive alerts while all apps in our environment's begin speaking with PLG. The AM UI should also be accessible via the frontend for administrators and developers to monitor/silence/create alerts.

**Acceptance Criteria:** 
_Create a list of functional outcomes that must be achieved to complete this issue_

- [ ] AM deployed in the production environment
- [ ] AM UI accessible from any environment (dev, staging, and production)
- [ ] AM alerts fire and route correctly from deployed environment
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
_Create a list of granular, specific work items that must be completed to deliver the desired outcomes of this issue_ 

- [x] Update `plg/deploy.sh` to deploy AM and handle any network config
- [x] Update `scripts/deploy-frontend.sh` to add network config to proxy AM in prod from all environments.
- [x] Update nginx conf file to proxy AM in prod
- [x] Add/update a manifest for AM, be sure to use the binary buildpack and deploy AM as a standalone binary for consistency and templating capabilities.
- [x] Upload the newest `Logs` dashboard to Grafana
- [x] Run Testing Checklist and confirm all tests pass

**Notes:**
_Add additional useful information, such as related issues and functionality that isn't covered by this specific issue, and other considerations that will be helpful for anyone reading this_ 

- _Note 1_
- _Note 2_
- _Note 3_

**Supporting Documentation:**
_Please include any relevant log snippets/files/screen shots_

- _Doc 1_
- _Doc 2_

**Open Questions:**
_Please include any questions or decisions that must be made before beginning work or to confidently call this issue complete_ 

- _Open Question 1_
- _Open Question 2_

### PR DESCRIPTION
**Pull request by elipe17**
## Summary of Changes
- Updated alertmanager manifest to pull alertmanager binary and start it in monolith mode
- Updated `plg/deploy.sh` to deploy alertmanager and handle networking
- Fixed some prometheus alert config errors
- Updated alertmanager config to notify receivers when an alert/group of alerts has been resolved
Pull request closes #3254

## How to Test
1. Deploy this PR to a dev environment. Note for testing purposes alertmanager is deployed in a dev environment. 
2. Log in with the CF CLI and run `cf add-network-policy alertmanager tdp-frontend-<ENV> --protocol tcp --port 80` and `cf add-network-policy tdp-frontend-<ENV> alertmanager --protocol tcp --port 8080` where `<ENV>` should be replaced with `raft`, or `qasp`, etc...
3. Log into the frontend as an OFA System Admin or Developer
4. Verify the `Alerts` tab is visible and proxies the alertmanager UI when clicked
5. See screenshots below for alerts that fired from the raft environment and the associated emails that were received

Screenshot 2024-11-18 at 9 28 22 AM
Screenshot 2024-11-18 at 10 01 48 AM

Screenshot 2024-11-19 at 2 05 14 PM
Screenshot 2024-11-19 at 2 05 19 PM

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
- [x] AM deployed in the production environment
- [x] AM UI accessible from any environment (dev, staging, and production)
- [x] AM alerts fire and route correctly from deployed environment
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [x] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by jtimpe — APPROVED** [review]
Everything appears to be running post-deployment and the `admin_team_emails` and `dev_team_emails` vars look to be correctly substituted.

**Review by raftmsohani — APPROVED** [review]
LGTM!

**Comment by ADPennington** [comment]
@elipe17 some merge conflicts on this one. please ping me when ready again

**Comment by ADPennington** [comment]
@elipe17 is there an easy way to trigger the alert manager in the deployed environment?

**Review by ADPennington — APPROVED** [review]
LGTM @elipe17 thank you. Please note:

- @ttran-hub and I need to be added to alert emails in prod. 
- We will keep an eye on this scenario: ` we won't receive notifications of a backend outage  if Prometheus or Alertmanager themselves go down.` and consider your following suggestion if needed (because this would require more RAM):
> > We can even remedy that situation by having high availability (HA) deployments of those apps. Then the probability of a PLG outage would be extremely low`

**Pull request merged**
