### PR TITLE
No more robots

### LINKED ISSUE #2238: As tech lead, I need "low" findings from WebInspect Oct 2022 scan addressed
**Description:**
ACF OCIO performs monthly security scans on prod using [WebInspect](https://www.microfocus.com/media/data-sheet/webinspect_automated_dynamic_application_security_testing_ds.pdf), and has a few low findings for Oct 2022:

scan

More information is on [p. 8+ here](https://hhsgov.sharepoint.com/:b:/r/sites/TANFDataPortalOFA/Shared%20Documents/compliance/TDP%20Security%20Scans/WebInspect/Oct2022/ACF-External%20Prod%20-%20tanfdata.acf.hhs.gov%202022-10-29T10.07.23.pdf?csf=1&web=1&e=U4ngvO) :lock: 

**Acceptance Criteria:** 
- [ ] source of issue identified
- [ ] source of issue resolved or documented
- [ ] Testing Checklist has been run and all tests pass
- [ ] README is updated, if necessary

**Tasks:**
- [ ] investigate root cause
- [ ] look into why this isnt showing up in owasp scans
- [ ] resolve/document
- [ ] Run Testing Checklist and confirm all tests pass

### PR DESCRIPTION
**Pull request by n0remac**
## Summary of Changes
_Provide a brief summary of changes_
Pull request closes #2238 

As per Dev sync on 11/15/22 we agreed to remove the robots.txt if we are getting no use from it.

### CODE REVIEW

**Review by andrew-jameson — APPROVED** [review]

**Comment by andrew-jameson** [comment]
Pending OCIO per standup 11/23

**Comment by andrew-jameson** [comment]
> Pending OCIO per standup 11/23

@ADPennington Any update here? Let me know if/when this can be merged

**Review by ADPennington — APPROVED** [review]
@n0remac approved per OCIO on 1/10/23 cc: @tdrammeh1 @ttran-hub.

ready to merge @andrew-jameson

**Comment by andrew-jameson** [comment]
This is a test.

**Pull request merged**
